/*
ProxMox VE API

ProxMox VE API

API version: 8.0
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the RebootContainerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RebootContainerRequest{}

// RebootContainerRequest struct for RebootContainerRequest
type RebootContainerRequest struct {
	// Wait maximal timeout seconds for the shutdown.
	Timeout *int64 `json:"timeout,omitempty"`
}

// NewRebootContainerRequest instantiates a new RebootContainerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRebootContainerRequest() *RebootContainerRequest {
	this := RebootContainerRequest{}
	return &this
}

// NewRebootContainerRequestWithDefaults instantiates a new RebootContainerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRebootContainerRequestWithDefaults() *RebootContainerRequest {
	this := RebootContainerRequest{}
	return &this
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *RebootContainerRequest) GetTimeout() int64 {
	if o == nil || IsNil(o.Timeout) {
		var ret int64
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RebootContainerRequest) GetTimeoutOk() (*int64, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *RebootContainerRequest) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int64 and assigns it to the Timeout field.
func (o *RebootContainerRequest) SetTimeout(v int64) {
	o.Timeout = &v
}

func (o RebootContainerRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RebootContainerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	return toSerialize, nil
}

type NullableRebootContainerRequest struct {
	value *RebootContainerRequest
	isSet bool
}

func (v NullableRebootContainerRequest) Get() *RebootContainerRequest {
	return v.value
}

func (v *NullableRebootContainerRequest) Set(val *RebootContainerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRebootContainerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRebootContainerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRebootContainerRequest(val *RebootContainerRequest) *NullableRebootContainerRequest {
	return &NullableRebootContainerRequest{value: val, isSet: true}
}

func (v NullableRebootContainerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRebootContainerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


