/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the CreateVMRequestNuma0 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVMRequestNuma0{}

// CreateVMRequestNuma0 struct for CreateVMRequestNuma0
type CreateVMRequestNuma0 struct {
	Cpus string `json:"cpus"`
	Hostnodes *string `json:"hostnodes,omitempty"`
	Memory *float32 `json:"memory,omitempty"`
	Policy *string `json:"policy,omitempty"`
}

// NewCreateVMRequestNuma0 instantiates a new CreateVMRequestNuma0 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVMRequestNuma0(cpus string) *CreateVMRequestNuma0 {
	this := CreateVMRequestNuma0{}
	this.Cpus = cpus
	return &this
}

// NewCreateVMRequestNuma0WithDefaults instantiates a new CreateVMRequestNuma0 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVMRequestNuma0WithDefaults() *CreateVMRequestNuma0 {
	this := CreateVMRequestNuma0{}
	return &this
}

// GetCpus returns the Cpus field value
func (o *CreateVMRequestNuma0) GetCpus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cpus
}

// GetCpusOk returns a tuple with the Cpus field value
// and a boolean to check if the value has been set.
func (o *CreateVMRequestNuma0) GetCpusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpus, true
}

// SetCpus sets field value
func (o *CreateVMRequestNuma0) SetCpus(v string) {
	o.Cpus = v
}

// GetHostnodes returns the Hostnodes field value if set, zero value otherwise.
func (o *CreateVMRequestNuma0) GetHostnodes() string {
	if o == nil || IsNil(o.Hostnodes) {
		var ret string
		return ret
	}
	return *o.Hostnodes
}

// GetHostnodesOk returns a tuple with the Hostnodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestNuma0) GetHostnodesOk() (*string, bool) {
	if o == nil || IsNil(o.Hostnodes) {
		return nil, false
	}
	return o.Hostnodes, true
}

// HasHostnodes returns a boolean if a field has been set.
func (o *CreateVMRequestNuma0) HasHostnodes() bool {
	if o != nil && !IsNil(o.Hostnodes) {
		return true
	}

	return false
}

// SetHostnodes gets a reference to the given string and assigns it to the Hostnodes field.
func (o *CreateVMRequestNuma0) SetHostnodes(v string) {
	o.Hostnodes = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *CreateVMRequestNuma0) GetMemory() float32 {
	if o == nil || IsNil(o.Memory) {
		var ret float32
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestNuma0) GetMemoryOk() (*float32, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *CreateVMRequestNuma0) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given float32 and assigns it to the Memory field.
func (o *CreateVMRequestNuma0) SetMemory(v float32) {
	o.Memory = &v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *CreateVMRequestNuma0) GetPolicy() string {
	if o == nil || IsNil(o.Policy) {
		var ret string
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestNuma0) GetPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *CreateVMRequestNuma0) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given string and assigns it to the Policy field.
func (o *CreateVMRequestNuma0) SetPolicy(v string) {
	o.Policy = &v
}

func (o CreateVMRequestNuma0) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVMRequestNuma0) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cpus"] = o.Cpus
	if !IsNil(o.Hostnodes) {
		toSerialize["hostnodes"] = o.Hostnodes
	}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	return toSerialize, nil
}

type NullableCreateVMRequestNuma0 struct {
	value *CreateVMRequestNuma0
	isSet bool
}

func (v NullableCreateVMRequestNuma0) Get() *CreateVMRequestNuma0 {
	return v.value
}

func (v *NullableCreateVMRequestNuma0) Set(val *CreateVMRequestNuma0) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVMRequestNuma0) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVMRequestNuma0) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVMRequestNuma0(val *CreateVMRequestNuma0) *NullableCreateVMRequestNuma0 {
	return &NullableCreateVMRequestNuma0{value: val, isSet: true}
}

func (v NullableCreateVMRequestNuma0) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVMRequestNuma0) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


