/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the CreateVMRequestSata0 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVMRequestSata0{}

// CreateVMRequestSata0 struct for CreateVMRequestSata0
type CreateVMRequestSata0 struct {
	Aio *string `json:"aio,omitempty"`
	Backup *bool `json:"backup,omitempty"`
	Bps *int64 `json:"bps,omitempty"`
	BpsMaxLength *int64 `json:"bps_max_length,omitempty"`
	BpsRd *int64 `json:"bps_rd,omitempty"`
	BpsRdMaxLength *int64 `json:"bps_rd_max_length,omitempty"`
	BpsWr *int64 `json:"bps_wr,omitempty"`
	BpsWrMaxLength *int64 `json:"bps_wr_max_length,omitempty"`
	Cache *string `json:"cache,omitempty"`
	Cyls *int64 `json:"cyls,omitempty"`
	DetectZeroes *bool `json:"detect_zeroes,omitempty"`
	Discard *string `json:"discard,omitempty"`
	File string `json:"file"`
	Format *string `json:"format,omitempty"`
	Heads *int64 `json:"heads,omitempty"`
	ImportFrom *string `json:"import-from,omitempty"`
	Iops *int64 `json:"iops,omitempty"`
	IopsMax *int64 `json:"iops_max,omitempty"`
	IopsMaxLength *int64 `json:"iops_max_length,omitempty"`
	IopsRd *int64 `json:"iops_rd,omitempty"`
	IopsRdMax *int64 `json:"iops_rd_max,omitempty"`
	IopsRdMaxLength *int64 `json:"iops_rd_max_length,omitempty"`
	IopsWr *int64 `json:"iops_wr,omitempty"`
	IopsWrMax *int64 `json:"iops_wr_max,omitempty"`
	IopsWrMaxLength *int64 `json:"iops_wr_max_length,omitempty"`
	Mbps *float32 `json:"mbps,omitempty"`
	MbpsMax *float32 `json:"mbps_max,omitempty"`
	MbpsRd *float32 `json:"mbps_rd,omitempty"`
	MbpsRdMax *float32 `json:"mbps_rd_max,omitempty"`
	MbpsWr *float32 `json:"mbps_wr,omitempty"`
	MbpsWrMax *float32 `json:"mbps_wr_max,omitempty"`
	Media *string `json:"media,omitempty"`
	Replicate *bool `json:"replicate,omitempty"`
	Rerror *string `json:"rerror,omitempty"`
	Secs *int64 `json:"secs,omitempty"`
	Serial *string `json:"serial,omitempty"`
	Shared *bool `json:"shared,omitempty"`
	Size *string `json:"size,omitempty"`
	Snapshot *bool `json:"snapshot,omitempty"`
	Ssd *bool `json:"ssd,omitempty"`
	Trans *string `json:"trans,omitempty"`
	Werror *string `json:"werror,omitempty"`
	Wwn *string `json:"wwn,omitempty"`
}

// NewCreateVMRequestSata0 instantiates a new CreateVMRequestSata0 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVMRequestSata0(file string) *CreateVMRequestSata0 {
	this := CreateVMRequestSata0{}
	this.File = file
	return &this
}

// NewCreateVMRequestSata0WithDefaults instantiates a new CreateVMRequestSata0 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVMRequestSata0WithDefaults() *CreateVMRequestSata0 {
	this := CreateVMRequestSata0{}
	return &this
}

// GetAio returns the Aio field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetAio() string {
	if o == nil || IsNil(o.Aio) {
		var ret string
		return ret
	}
	return *o.Aio
}

// GetAioOk returns a tuple with the Aio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetAioOk() (*string, bool) {
	if o == nil || IsNil(o.Aio) {
		return nil, false
	}
	return o.Aio, true
}

// HasAio returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasAio() bool {
	if o != nil && !IsNil(o.Aio) {
		return true
	}

	return false
}

// SetAio gets a reference to the given string and assigns it to the Aio field.
func (o *CreateVMRequestSata0) SetAio(v string) {
	o.Aio = &v
}

// GetBackup returns the Backup field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetBackup() bool {
	if o == nil || IsNil(o.Backup) {
		var ret bool
		return ret
	}
	return *o.Backup
}

// GetBackupOk returns a tuple with the Backup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetBackupOk() (*bool, bool) {
	if o == nil || IsNil(o.Backup) {
		return nil, false
	}
	return o.Backup, true
}

// HasBackup returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasBackup() bool {
	if o != nil && !IsNil(o.Backup) {
		return true
	}

	return false
}

// SetBackup gets a reference to the given bool and assigns it to the Backup field.
func (o *CreateVMRequestSata0) SetBackup(v bool) {
	o.Backup = &v
}

// GetBps returns the Bps field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetBps() int64 {
	if o == nil || IsNil(o.Bps) {
		var ret int64
		return ret
	}
	return *o.Bps
}

// GetBpsOk returns a tuple with the Bps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetBpsOk() (*int64, bool) {
	if o == nil || IsNil(o.Bps) {
		return nil, false
	}
	return o.Bps, true
}

// HasBps returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasBps() bool {
	if o != nil && !IsNil(o.Bps) {
		return true
	}

	return false
}

// SetBps gets a reference to the given int64 and assigns it to the Bps field.
func (o *CreateVMRequestSata0) SetBps(v int64) {
	o.Bps = &v
}

// GetBpsMaxLength returns the BpsMaxLength field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetBpsMaxLength() int64 {
	if o == nil || IsNil(o.BpsMaxLength) {
		var ret int64
		return ret
	}
	return *o.BpsMaxLength
}

// GetBpsMaxLengthOk returns a tuple with the BpsMaxLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetBpsMaxLengthOk() (*int64, bool) {
	if o == nil || IsNil(o.BpsMaxLength) {
		return nil, false
	}
	return o.BpsMaxLength, true
}

// HasBpsMaxLength returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasBpsMaxLength() bool {
	if o != nil && !IsNil(o.BpsMaxLength) {
		return true
	}

	return false
}

// SetBpsMaxLength gets a reference to the given int64 and assigns it to the BpsMaxLength field.
func (o *CreateVMRequestSata0) SetBpsMaxLength(v int64) {
	o.BpsMaxLength = &v
}

// GetBpsRd returns the BpsRd field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetBpsRd() int64 {
	if o == nil || IsNil(o.BpsRd) {
		var ret int64
		return ret
	}
	return *o.BpsRd
}

// GetBpsRdOk returns a tuple with the BpsRd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetBpsRdOk() (*int64, bool) {
	if o == nil || IsNil(o.BpsRd) {
		return nil, false
	}
	return o.BpsRd, true
}

// HasBpsRd returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasBpsRd() bool {
	if o != nil && !IsNil(o.BpsRd) {
		return true
	}

	return false
}

// SetBpsRd gets a reference to the given int64 and assigns it to the BpsRd field.
func (o *CreateVMRequestSata0) SetBpsRd(v int64) {
	o.BpsRd = &v
}

// GetBpsRdMaxLength returns the BpsRdMaxLength field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetBpsRdMaxLength() int64 {
	if o == nil || IsNil(o.BpsRdMaxLength) {
		var ret int64
		return ret
	}
	return *o.BpsRdMaxLength
}

// GetBpsRdMaxLengthOk returns a tuple with the BpsRdMaxLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetBpsRdMaxLengthOk() (*int64, bool) {
	if o == nil || IsNil(o.BpsRdMaxLength) {
		return nil, false
	}
	return o.BpsRdMaxLength, true
}

// HasBpsRdMaxLength returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasBpsRdMaxLength() bool {
	if o != nil && !IsNil(o.BpsRdMaxLength) {
		return true
	}

	return false
}

// SetBpsRdMaxLength gets a reference to the given int64 and assigns it to the BpsRdMaxLength field.
func (o *CreateVMRequestSata0) SetBpsRdMaxLength(v int64) {
	o.BpsRdMaxLength = &v
}

// GetBpsWr returns the BpsWr field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetBpsWr() int64 {
	if o == nil || IsNil(o.BpsWr) {
		var ret int64
		return ret
	}
	return *o.BpsWr
}

// GetBpsWrOk returns a tuple with the BpsWr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetBpsWrOk() (*int64, bool) {
	if o == nil || IsNil(o.BpsWr) {
		return nil, false
	}
	return o.BpsWr, true
}

// HasBpsWr returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasBpsWr() bool {
	if o != nil && !IsNil(o.BpsWr) {
		return true
	}

	return false
}

// SetBpsWr gets a reference to the given int64 and assigns it to the BpsWr field.
func (o *CreateVMRequestSata0) SetBpsWr(v int64) {
	o.BpsWr = &v
}

// GetBpsWrMaxLength returns the BpsWrMaxLength field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetBpsWrMaxLength() int64 {
	if o == nil || IsNil(o.BpsWrMaxLength) {
		var ret int64
		return ret
	}
	return *o.BpsWrMaxLength
}

// GetBpsWrMaxLengthOk returns a tuple with the BpsWrMaxLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetBpsWrMaxLengthOk() (*int64, bool) {
	if o == nil || IsNil(o.BpsWrMaxLength) {
		return nil, false
	}
	return o.BpsWrMaxLength, true
}

// HasBpsWrMaxLength returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasBpsWrMaxLength() bool {
	if o != nil && !IsNil(o.BpsWrMaxLength) {
		return true
	}

	return false
}

// SetBpsWrMaxLength gets a reference to the given int64 and assigns it to the BpsWrMaxLength field.
func (o *CreateVMRequestSata0) SetBpsWrMaxLength(v int64) {
	o.BpsWrMaxLength = &v
}

// GetCache returns the Cache field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetCache() string {
	if o == nil || IsNil(o.Cache) {
		var ret string
		return ret
	}
	return *o.Cache
}

// GetCacheOk returns a tuple with the Cache field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetCacheOk() (*string, bool) {
	if o == nil || IsNil(o.Cache) {
		return nil, false
	}
	return o.Cache, true
}

// HasCache returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasCache() bool {
	if o != nil && !IsNil(o.Cache) {
		return true
	}

	return false
}

// SetCache gets a reference to the given string and assigns it to the Cache field.
func (o *CreateVMRequestSata0) SetCache(v string) {
	o.Cache = &v
}

// GetCyls returns the Cyls field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetCyls() int64 {
	if o == nil || IsNil(o.Cyls) {
		var ret int64
		return ret
	}
	return *o.Cyls
}

// GetCylsOk returns a tuple with the Cyls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetCylsOk() (*int64, bool) {
	if o == nil || IsNil(o.Cyls) {
		return nil, false
	}
	return o.Cyls, true
}

// HasCyls returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasCyls() bool {
	if o != nil && !IsNil(o.Cyls) {
		return true
	}

	return false
}

// SetCyls gets a reference to the given int64 and assigns it to the Cyls field.
func (o *CreateVMRequestSata0) SetCyls(v int64) {
	o.Cyls = &v
}

// GetDetectZeroes returns the DetectZeroes field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetDetectZeroes() bool {
	if o == nil || IsNil(o.DetectZeroes) {
		var ret bool
		return ret
	}
	return *o.DetectZeroes
}

// GetDetectZeroesOk returns a tuple with the DetectZeroes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetDetectZeroesOk() (*bool, bool) {
	if o == nil || IsNil(o.DetectZeroes) {
		return nil, false
	}
	return o.DetectZeroes, true
}

// HasDetectZeroes returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasDetectZeroes() bool {
	if o != nil && !IsNil(o.DetectZeroes) {
		return true
	}

	return false
}

// SetDetectZeroes gets a reference to the given bool and assigns it to the DetectZeroes field.
func (o *CreateVMRequestSata0) SetDetectZeroes(v bool) {
	o.DetectZeroes = &v
}

// GetDiscard returns the Discard field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetDiscard() string {
	if o == nil || IsNil(o.Discard) {
		var ret string
		return ret
	}
	return *o.Discard
}

// GetDiscardOk returns a tuple with the Discard field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetDiscardOk() (*string, bool) {
	if o == nil || IsNil(o.Discard) {
		return nil, false
	}
	return o.Discard, true
}

// HasDiscard returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasDiscard() bool {
	if o != nil && !IsNil(o.Discard) {
		return true
	}

	return false
}

// SetDiscard gets a reference to the given string and assigns it to the Discard field.
func (o *CreateVMRequestSata0) SetDiscard(v string) {
	o.Discard = &v
}

// GetFile returns the File field value
func (o *CreateVMRequestSata0) GetFile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *CreateVMRequestSata0) SetFile(v string) {
	o.File = v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *CreateVMRequestSata0) SetFormat(v string) {
	o.Format = &v
}

// GetHeads returns the Heads field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetHeads() int64 {
	if o == nil || IsNil(o.Heads) {
		var ret int64
		return ret
	}
	return *o.Heads
}

// GetHeadsOk returns a tuple with the Heads field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetHeadsOk() (*int64, bool) {
	if o == nil || IsNil(o.Heads) {
		return nil, false
	}
	return o.Heads, true
}

// HasHeads returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasHeads() bool {
	if o != nil && !IsNil(o.Heads) {
		return true
	}

	return false
}

// SetHeads gets a reference to the given int64 and assigns it to the Heads field.
func (o *CreateVMRequestSata0) SetHeads(v int64) {
	o.Heads = &v
}

// GetImportFrom returns the ImportFrom field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetImportFrom() string {
	if o == nil || IsNil(o.ImportFrom) {
		var ret string
		return ret
	}
	return *o.ImportFrom
}

// GetImportFromOk returns a tuple with the ImportFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetImportFromOk() (*string, bool) {
	if o == nil || IsNil(o.ImportFrom) {
		return nil, false
	}
	return o.ImportFrom, true
}

// HasImportFrom returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasImportFrom() bool {
	if o != nil && !IsNil(o.ImportFrom) {
		return true
	}

	return false
}

// SetImportFrom gets a reference to the given string and assigns it to the ImportFrom field.
func (o *CreateVMRequestSata0) SetImportFrom(v string) {
	o.ImportFrom = &v
}

// GetIops returns the Iops field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetIops() int64 {
	if o == nil || IsNil(o.Iops) {
		var ret int64
		return ret
	}
	return *o.Iops
}

// GetIopsOk returns a tuple with the Iops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetIopsOk() (*int64, bool) {
	if o == nil || IsNil(o.Iops) {
		return nil, false
	}
	return o.Iops, true
}

// HasIops returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasIops() bool {
	if o != nil && !IsNil(o.Iops) {
		return true
	}

	return false
}

// SetIops gets a reference to the given int64 and assigns it to the Iops field.
func (o *CreateVMRequestSata0) SetIops(v int64) {
	o.Iops = &v
}

// GetIopsMax returns the IopsMax field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetIopsMax() int64 {
	if o == nil || IsNil(o.IopsMax) {
		var ret int64
		return ret
	}
	return *o.IopsMax
}

// GetIopsMaxOk returns a tuple with the IopsMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetIopsMaxOk() (*int64, bool) {
	if o == nil || IsNil(o.IopsMax) {
		return nil, false
	}
	return o.IopsMax, true
}

// HasIopsMax returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasIopsMax() bool {
	if o != nil && !IsNil(o.IopsMax) {
		return true
	}

	return false
}

// SetIopsMax gets a reference to the given int64 and assigns it to the IopsMax field.
func (o *CreateVMRequestSata0) SetIopsMax(v int64) {
	o.IopsMax = &v
}

// GetIopsMaxLength returns the IopsMaxLength field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetIopsMaxLength() int64 {
	if o == nil || IsNil(o.IopsMaxLength) {
		var ret int64
		return ret
	}
	return *o.IopsMaxLength
}

// GetIopsMaxLengthOk returns a tuple with the IopsMaxLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetIopsMaxLengthOk() (*int64, bool) {
	if o == nil || IsNil(o.IopsMaxLength) {
		return nil, false
	}
	return o.IopsMaxLength, true
}

// HasIopsMaxLength returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasIopsMaxLength() bool {
	if o != nil && !IsNil(o.IopsMaxLength) {
		return true
	}

	return false
}

// SetIopsMaxLength gets a reference to the given int64 and assigns it to the IopsMaxLength field.
func (o *CreateVMRequestSata0) SetIopsMaxLength(v int64) {
	o.IopsMaxLength = &v
}

// GetIopsRd returns the IopsRd field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetIopsRd() int64 {
	if o == nil || IsNil(o.IopsRd) {
		var ret int64
		return ret
	}
	return *o.IopsRd
}

// GetIopsRdOk returns a tuple with the IopsRd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetIopsRdOk() (*int64, bool) {
	if o == nil || IsNil(o.IopsRd) {
		return nil, false
	}
	return o.IopsRd, true
}

// HasIopsRd returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasIopsRd() bool {
	if o != nil && !IsNil(o.IopsRd) {
		return true
	}

	return false
}

// SetIopsRd gets a reference to the given int64 and assigns it to the IopsRd field.
func (o *CreateVMRequestSata0) SetIopsRd(v int64) {
	o.IopsRd = &v
}

// GetIopsRdMax returns the IopsRdMax field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetIopsRdMax() int64 {
	if o == nil || IsNil(o.IopsRdMax) {
		var ret int64
		return ret
	}
	return *o.IopsRdMax
}

// GetIopsRdMaxOk returns a tuple with the IopsRdMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetIopsRdMaxOk() (*int64, bool) {
	if o == nil || IsNil(o.IopsRdMax) {
		return nil, false
	}
	return o.IopsRdMax, true
}

// HasIopsRdMax returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasIopsRdMax() bool {
	if o != nil && !IsNil(o.IopsRdMax) {
		return true
	}

	return false
}

// SetIopsRdMax gets a reference to the given int64 and assigns it to the IopsRdMax field.
func (o *CreateVMRequestSata0) SetIopsRdMax(v int64) {
	o.IopsRdMax = &v
}

// GetIopsRdMaxLength returns the IopsRdMaxLength field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetIopsRdMaxLength() int64 {
	if o == nil || IsNil(o.IopsRdMaxLength) {
		var ret int64
		return ret
	}
	return *o.IopsRdMaxLength
}

// GetIopsRdMaxLengthOk returns a tuple with the IopsRdMaxLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetIopsRdMaxLengthOk() (*int64, bool) {
	if o == nil || IsNil(o.IopsRdMaxLength) {
		return nil, false
	}
	return o.IopsRdMaxLength, true
}

// HasIopsRdMaxLength returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasIopsRdMaxLength() bool {
	if o != nil && !IsNil(o.IopsRdMaxLength) {
		return true
	}

	return false
}

// SetIopsRdMaxLength gets a reference to the given int64 and assigns it to the IopsRdMaxLength field.
func (o *CreateVMRequestSata0) SetIopsRdMaxLength(v int64) {
	o.IopsRdMaxLength = &v
}

// GetIopsWr returns the IopsWr field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetIopsWr() int64 {
	if o == nil || IsNil(o.IopsWr) {
		var ret int64
		return ret
	}
	return *o.IopsWr
}

// GetIopsWrOk returns a tuple with the IopsWr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetIopsWrOk() (*int64, bool) {
	if o == nil || IsNil(o.IopsWr) {
		return nil, false
	}
	return o.IopsWr, true
}

// HasIopsWr returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasIopsWr() bool {
	if o != nil && !IsNil(o.IopsWr) {
		return true
	}

	return false
}

// SetIopsWr gets a reference to the given int64 and assigns it to the IopsWr field.
func (o *CreateVMRequestSata0) SetIopsWr(v int64) {
	o.IopsWr = &v
}

// GetIopsWrMax returns the IopsWrMax field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetIopsWrMax() int64 {
	if o == nil || IsNil(o.IopsWrMax) {
		var ret int64
		return ret
	}
	return *o.IopsWrMax
}

// GetIopsWrMaxOk returns a tuple with the IopsWrMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetIopsWrMaxOk() (*int64, bool) {
	if o == nil || IsNil(o.IopsWrMax) {
		return nil, false
	}
	return o.IopsWrMax, true
}

// HasIopsWrMax returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasIopsWrMax() bool {
	if o != nil && !IsNil(o.IopsWrMax) {
		return true
	}

	return false
}

// SetIopsWrMax gets a reference to the given int64 and assigns it to the IopsWrMax field.
func (o *CreateVMRequestSata0) SetIopsWrMax(v int64) {
	o.IopsWrMax = &v
}

// GetIopsWrMaxLength returns the IopsWrMaxLength field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetIopsWrMaxLength() int64 {
	if o == nil || IsNil(o.IopsWrMaxLength) {
		var ret int64
		return ret
	}
	return *o.IopsWrMaxLength
}

// GetIopsWrMaxLengthOk returns a tuple with the IopsWrMaxLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetIopsWrMaxLengthOk() (*int64, bool) {
	if o == nil || IsNil(o.IopsWrMaxLength) {
		return nil, false
	}
	return o.IopsWrMaxLength, true
}

// HasIopsWrMaxLength returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasIopsWrMaxLength() bool {
	if o != nil && !IsNil(o.IopsWrMaxLength) {
		return true
	}

	return false
}

// SetIopsWrMaxLength gets a reference to the given int64 and assigns it to the IopsWrMaxLength field.
func (o *CreateVMRequestSata0) SetIopsWrMaxLength(v int64) {
	o.IopsWrMaxLength = &v
}

// GetMbps returns the Mbps field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetMbps() float32 {
	if o == nil || IsNil(o.Mbps) {
		var ret float32
		return ret
	}
	return *o.Mbps
}

// GetMbpsOk returns a tuple with the Mbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetMbpsOk() (*float32, bool) {
	if o == nil || IsNil(o.Mbps) {
		return nil, false
	}
	return o.Mbps, true
}

// HasMbps returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasMbps() bool {
	if o != nil && !IsNil(o.Mbps) {
		return true
	}

	return false
}

// SetMbps gets a reference to the given float32 and assigns it to the Mbps field.
func (o *CreateVMRequestSata0) SetMbps(v float32) {
	o.Mbps = &v
}

// GetMbpsMax returns the MbpsMax field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetMbpsMax() float32 {
	if o == nil || IsNil(o.MbpsMax) {
		var ret float32
		return ret
	}
	return *o.MbpsMax
}

// GetMbpsMaxOk returns a tuple with the MbpsMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetMbpsMaxOk() (*float32, bool) {
	if o == nil || IsNil(o.MbpsMax) {
		return nil, false
	}
	return o.MbpsMax, true
}

// HasMbpsMax returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasMbpsMax() bool {
	if o != nil && !IsNil(o.MbpsMax) {
		return true
	}

	return false
}

// SetMbpsMax gets a reference to the given float32 and assigns it to the MbpsMax field.
func (o *CreateVMRequestSata0) SetMbpsMax(v float32) {
	o.MbpsMax = &v
}

// GetMbpsRd returns the MbpsRd field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetMbpsRd() float32 {
	if o == nil || IsNil(o.MbpsRd) {
		var ret float32
		return ret
	}
	return *o.MbpsRd
}

// GetMbpsRdOk returns a tuple with the MbpsRd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetMbpsRdOk() (*float32, bool) {
	if o == nil || IsNil(o.MbpsRd) {
		return nil, false
	}
	return o.MbpsRd, true
}

// HasMbpsRd returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasMbpsRd() bool {
	if o != nil && !IsNil(o.MbpsRd) {
		return true
	}

	return false
}

// SetMbpsRd gets a reference to the given float32 and assigns it to the MbpsRd field.
func (o *CreateVMRequestSata0) SetMbpsRd(v float32) {
	o.MbpsRd = &v
}

// GetMbpsRdMax returns the MbpsRdMax field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetMbpsRdMax() float32 {
	if o == nil || IsNil(o.MbpsRdMax) {
		var ret float32
		return ret
	}
	return *o.MbpsRdMax
}

// GetMbpsRdMaxOk returns a tuple with the MbpsRdMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetMbpsRdMaxOk() (*float32, bool) {
	if o == nil || IsNil(o.MbpsRdMax) {
		return nil, false
	}
	return o.MbpsRdMax, true
}

// HasMbpsRdMax returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasMbpsRdMax() bool {
	if o != nil && !IsNil(o.MbpsRdMax) {
		return true
	}

	return false
}

// SetMbpsRdMax gets a reference to the given float32 and assigns it to the MbpsRdMax field.
func (o *CreateVMRequestSata0) SetMbpsRdMax(v float32) {
	o.MbpsRdMax = &v
}

// GetMbpsWr returns the MbpsWr field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetMbpsWr() float32 {
	if o == nil || IsNil(o.MbpsWr) {
		var ret float32
		return ret
	}
	return *o.MbpsWr
}

// GetMbpsWrOk returns a tuple with the MbpsWr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetMbpsWrOk() (*float32, bool) {
	if o == nil || IsNil(o.MbpsWr) {
		return nil, false
	}
	return o.MbpsWr, true
}

// HasMbpsWr returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasMbpsWr() bool {
	if o != nil && !IsNil(o.MbpsWr) {
		return true
	}

	return false
}

// SetMbpsWr gets a reference to the given float32 and assigns it to the MbpsWr field.
func (o *CreateVMRequestSata0) SetMbpsWr(v float32) {
	o.MbpsWr = &v
}

// GetMbpsWrMax returns the MbpsWrMax field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetMbpsWrMax() float32 {
	if o == nil || IsNil(o.MbpsWrMax) {
		var ret float32
		return ret
	}
	return *o.MbpsWrMax
}

// GetMbpsWrMaxOk returns a tuple with the MbpsWrMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetMbpsWrMaxOk() (*float32, bool) {
	if o == nil || IsNil(o.MbpsWrMax) {
		return nil, false
	}
	return o.MbpsWrMax, true
}

// HasMbpsWrMax returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasMbpsWrMax() bool {
	if o != nil && !IsNil(o.MbpsWrMax) {
		return true
	}

	return false
}

// SetMbpsWrMax gets a reference to the given float32 and assigns it to the MbpsWrMax field.
func (o *CreateVMRequestSata0) SetMbpsWrMax(v float32) {
	o.MbpsWrMax = &v
}

// GetMedia returns the Media field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetMedia() string {
	if o == nil || IsNil(o.Media) {
		var ret string
		return ret
	}
	return *o.Media
}

// GetMediaOk returns a tuple with the Media field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetMediaOk() (*string, bool) {
	if o == nil || IsNil(o.Media) {
		return nil, false
	}
	return o.Media, true
}

// HasMedia returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasMedia() bool {
	if o != nil && !IsNil(o.Media) {
		return true
	}

	return false
}

// SetMedia gets a reference to the given string and assigns it to the Media field.
func (o *CreateVMRequestSata0) SetMedia(v string) {
	o.Media = &v
}

// GetReplicate returns the Replicate field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetReplicate() bool {
	if o == nil || IsNil(o.Replicate) {
		var ret bool
		return ret
	}
	return *o.Replicate
}

// GetReplicateOk returns a tuple with the Replicate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetReplicateOk() (*bool, bool) {
	if o == nil || IsNil(o.Replicate) {
		return nil, false
	}
	return o.Replicate, true
}

// HasReplicate returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasReplicate() bool {
	if o != nil && !IsNil(o.Replicate) {
		return true
	}

	return false
}

// SetReplicate gets a reference to the given bool and assigns it to the Replicate field.
func (o *CreateVMRequestSata0) SetReplicate(v bool) {
	o.Replicate = &v
}

// GetRerror returns the Rerror field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetRerror() string {
	if o == nil || IsNil(o.Rerror) {
		var ret string
		return ret
	}
	return *o.Rerror
}

// GetRerrorOk returns a tuple with the Rerror field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetRerrorOk() (*string, bool) {
	if o == nil || IsNil(o.Rerror) {
		return nil, false
	}
	return o.Rerror, true
}

// HasRerror returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasRerror() bool {
	if o != nil && !IsNil(o.Rerror) {
		return true
	}

	return false
}

// SetRerror gets a reference to the given string and assigns it to the Rerror field.
func (o *CreateVMRequestSata0) SetRerror(v string) {
	o.Rerror = &v
}

// GetSecs returns the Secs field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetSecs() int64 {
	if o == nil || IsNil(o.Secs) {
		var ret int64
		return ret
	}
	return *o.Secs
}

// GetSecsOk returns a tuple with the Secs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetSecsOk() (*int64, bool) {
	if o == nil || IsNil(o.Secs) {
		return nil, false
	}
	return o.Secs, true
}

// HasSecs returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasSecs() bool {
	if o != nil && !IsNil(o.Secs) {
		return true
	}

	return false
}

// SetSecs gets a reference to the given int64 and assigns it to the Secs field.
func (o *CreateVMRequestSata0) SetSecs(v int64) {
	o.Secs = &v
}

// GetSerial returns the Serial field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetSerial() string {
	if o == nil || IsNil(o.Serial) {
		var ret string
		return ret
	}
	return *o.Serial
}

// GetSerialOk returns a tuple with the Serial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetSerialOk() (*string, bool) {
	if o == nil || IsNil(o.Serial) {
		return nil, false
	}
	return o.Serial, true
}

// HasSerial returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasSerial() bool {
	if o != nil && !IsNil(o.Serial) {
		return true
	}

	return false
}

// SetSerial gets a reference to the given string and assigns it to the Serial field.
func (o *CreateVMRequestSata0) SetSerial(v string) {
	o.Serial = &v
}

// GetShared returns the Shared field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetShared() bool {
	if o == nil || IsNil(o.Shared) {
		var ret bool
		return ret
	}
	return *o.Shared
}

// GetSharedOk returns a tuple with the Shared field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetSharedOk() (*bool, bool) {
	if o == nil || IsNil(o.Shared) {
		return nil, false
	}
	return o.Shared, true
}

// HasShared returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasShared() bool {
	if o != nil && !IsNil(o.Shared) {
		return true
	}

	return false
}

// SetShared gets a reference to the given bool and assigns it to the Shared field.
func (o *CreateVMRequestSata0) SetShared(v bool) {
	o.Shared = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetSize() string {
	if o == nil || IsNil(o.Size) {
		var ret string
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetSizeOk() (*string, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given string and assigns it to the Size field.
func (o *CreateVMRequestSata0) SetSize(v string) {
	o.Size = &v
}

// GetSnapshot returns the Snapshot field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetSnapshot() bool {
	if o == nil || IsNil(o.Snapshot) {
		var ret bool
		return ret
	}
	return *o.Snapshot
}

// GetSnapshotOk returns a tuple with the Snapshot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetSnapshotOk() (*bool, bool) {
	if o == nil || IsNil(o.Snapshot) {
		return nil, false
	}
	return o.Snapshot, true
}

// HasSnapshot returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasSnapshot() bool {
	if o != nil && !IsNil(o.Snapshot) {
		return true
	}

	return false
}

// SetSnapshot gets a reference to the given bool and assigns it to the Snapshot field.
func (o *CreateVMRequestSata0) SetSnapshot(v bool) {
	o.Snapshot = &v
}

// GetSsd returns the Ssd field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetSsd() bool {
	if o == nil || IsNil(o.Ssd) {
		var ret bool
		return ret
	}
	return *o.Ssd
}

// GetSsdOk returns a tuple with the Ssd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetSsdOk() (*bool, bool) {
	if o == nil || IsNil(o.Ssd) {
		return nil, false
	}
	return o.Ssd, true
}

// HasSsd returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasSsd() bool {
	if o != nil && !IsNil(o.Ssd) {
		return true
	}

	return false
}

// SetSsd gets a reference to the given bool and assigns it to the Ssd field.
func (o *CreateVMRequestSata0) SetSsd(v bool) {
	o.Ssd = &v
}

// GetTrans returns the Trans field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetTrans() string {
	if o == nil || IsNil(o.Trans) {
		var ret string
		return ret
	}
	return *o.Trans
}

// GetTransOk returns a tuple with the Trans field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetTransOk() (*string, bool) {
	if o == nil || IsNil(o.Trans) {
		return nil, false
	}
	return o.Trans, true
}

// HasTrans returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasTrans() bool {
	if o != nil && !IsNil(o.Trans) {
		return true
	}

	return false
}

// SetTrans gets a reference to the given string and assigns it to the Trans field.
func (o *CreateVMRequestSata0) SetTrans(v string) {
	o.Trans = &v
}

// GetWerror returns the Werror field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetWerror() string {
	if o == nil || IsNil(o.Werror) {
		var ret string
		return ret
	}
	return *o.Werror
}

// GetWerrorOk returns a tuple with the Werror field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetWerrorOk() (*string, bool) {
	if o == nil || IsNil(o.Werror) {
		return nil, false
	}
	return o.Werror, true
}

// HasWerror returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasWerror() bool {
	if o != nil && !IsNil(o.Werror) {
		return true
	}

	return false
}

// SetWerror gets a reference to the given string and assigns it to the Werror field.
func (o *CreateVMRequestSata0) SetWerror(v string) {
	o.Werror = &v
}

// GetWwn returns the Wwn field value if set, zero value otherwise.
func (o *CreateVMRequestSata0) GetWwn() string {
	if o == nil || IsNil(o.Wwn) {
		var ret string
		return ret
	}
	return *o.Wwn
}

// GetWwnOk returns a tuple with the Wwn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSata0) GetWwnOk() (*string, bool) {
	if o == nil || IsNil(o.Wwn) {
		return nil, false
	}
	return o.Wwn, true
}

// HasWwn returns a boolean if a field has been set.
func (o *CreateVMRequestSata0) HasWwn() bool {
	if o != nil && !IsNil(o.Wwn) {
		return true
	}

	return false
}

// SetWwn gets a reference to the given string and assigns it to the Wwn field.
func (o *CreateVMRequestSata0) SetWwn(v string) {
	o.Wwn = &v
}

func (o CreateVMRequestSata0) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVMRequestSata0) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Aio) {
		toSerialize["aio"] = o.Aio
	}
	if !IsNil(o.Backup) {
		toSerialize["backup"] = o.Backup
	}
	if !IsNil(o.Bps) {
		toSerialize["bps"] = o.Bps
	}
	if !IsNil(o.BpsMaxLength) {
		toSerialize["bps_max_length"] = o.BpsMaxLength
	}
	if !IsNil(o.BpsRd) {
		toSerialize["bps_rd"] = o.BpsRd
	}
	if !IsNil(o.BpsRdMaxLength) {
		toSerialize["bps_rd_max_length"] = o.BpsRdMaxLength
	}
	if !IsNil(o.BpsWr) {
		toSerialize["bps_wr"] = o.BpsWr
	}
	if !IsNil(o.BpsWrMaxLength) {
		toSerialize["bps_wr_max_length"] = o.BpsWrMaxLength
	}
	if !IsNil(o.Cache) {
		toSerialize["cache"] = o.Cache
	}
	if !IsNil(o.Cyls) {
		toSerialize["cyls"] = o.Cyls
	}
	if !IsNil(o.DetectZeroes) {
		toSerialize["detect_zeroes"] = o.DetectZeroes
	}
	if !IsNil(o.Discard) {
		toSerialize["discard"] = o.Discard
	}
	toSerialize["file"] = o.File
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.Heads) {
		toSerialize["heads"] = o.Heads
	}
	if !IsNil(o.ImportFrom) {
		toSerialize["import-from"] = o.ImportFrom
	}
	if !IsNil(o.Iops) {
		toSerialize["iops"] = o.Iops
	}
	if !IsNil(o.IopsMax) {
		toSerialize["iops_max"] = o.IopsMax
	}
	if !IsNil(o.IopsMaxLength) {
		toSerialize["iops_max_length"] = o.IopsMaxLength
	}
	if !IsNil(o.IopsRd) {
		toSerialize["iops_rd"] = o.IopsRd
	}
	if !IsNil(o.IopsRdMax) {
		toSerialize["iops_rd_max"] = o.IopsRdMax
	}
	if !IsNil(o.IopsRdMaxLength) {
		toSerialize["iops_rd_max_length"] = o.IopsRdMaxLength
	}
	if !IsNil(o.IopsWr) {
		toSerialize["iops_wr"] = o.IopsWr
	}
	if !IsNil(o.IopsWrMax) {
		toSerialize["iops_wr_max"] = o.IopsWrMax
	}
	if !IsNil(o.IopsWrMaxLength) {
		toSerialize["iops_wr_max_length"] = o.IopsWrMaxLength
	}
	if !IsNil(o.Mbps) {
		toSerialize["mbps"] = o.Mbps
	}
	if !IsNil(o.MbpsMax) {
		toSerialize["mbps_max"] = o.MbpsMax
	}
	if !IsNil(o.MbpsRd) {
		toSerialize["mbps_rd"] = o.MbpsRd
	}
	if !IsNil(o.MbpsRdMax) {
		toSerialize["mbps_rd_max"] = o.MbpsRdMax
	}
	if !IsNil(o.MbpsWr) {
		toSerialize["mbps_wr"] = o.MbpsWr
	}
	if !IsNil(o.MbpsWrMax) {
		toSerialize["mbps_wr_max"] = o.MbpsWrMax
	}
	if !IsNil(o.Media) {
		toSerialize["media"] = o.Media
	}
	if !IsNil(o.Replicate) {
		toSerialize["replicate"] = o.Replicate
	}
	if !IsNil(o.Rerror) {
		toSerialize["rerror"] = o.Rerror
	}
	if !IsNil(o.Secs) {
		toSerialize["secs"] = o.Secs
	}
	if !IsNil(o.Serial) {
		toSerialize["serial"] = o.Serial
	}
	if !IsNil(o.Shared) {
		toSerialize["shared"] = o.Shared
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Snapshot) {
		toSerialize["snapshot"] = o.Snapshot
	}
	if !IsNil(o.Ssd) {
		toSerialize["ssd"] = o.Ssd
	}
	if !IsNil(o.Trans) {
		toSerialize["trans"] = o.Trans
	}
	if !IsNil(o.Werror) {
		toSerialize["werror"] = o.Werror
	}
	if !IsNil(o.Wwn) {
		toSerialize["wwn"] = o.Wwn
	}
	return toSerialize, nil
}

type NullableCreateVMRequestSata0 struct {
	value *CreateVMRequestSata0
	isSet bool
}

func (v NullableCreateVMRequestSata0) Get() *CreateVMRequestSata0 {
	return v.value
}

func (v *NullableCreateVMRequestSata0) Set(val *CreateVMRequestSata0) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVMRequestSata0) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVMRequestSata0) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVMRequestSata0(val *CreateVMRequestSata0) *NullableCreateVMRequestSata0 {
	return &NullableCreateVMRequestSata0{value: val, isSet: true}
}

func (v NullableCreateVMRequestSata0) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVMRequestSata0) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


