/*
ProxMox VE API

ProxMox VE API

API version: 8.0
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the GetVMConfig200ResponseDataRng0 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVMConfig200ResponseDataRng0{}

// GetVMConfig200ResponseDataRng0 struct for GetVMConfig200ResponseDataRng0
type GetVMConfig200ResponseDataRng0 struct {
	// Maximum bytes of entropy allowed to get injected into the guest every 'period' milliseconds. Prefer a lower value when using '/dev/random' as source. Use `0` to disable limiting (potentially dangerous!).
	MaxBytes *int64 `json:"max_bytes,omitempty"`
	// Every 'period' milliseconds the entropy-injection quota is reset, allowing the guest to retrieve another 'max_bytes' of entropy.
	Period *int64 `json:"period,omitempty"`
	// The file on the host to gather entropy from. In most cases '/dev/urandom' should be preferred over '/dev/random' to avoid entropy-starvation issues on the host. Using urandom does *not* decrease security in any meaningful way, as it's still seeded from real entropy, and the bytes provided will most likely be mixed with real entropy on the guest as well. '/dev/hwrng' can be used to pass through a hardware RNG from the host.
	Source *string `json:"source,omitempty"`
}

// NewGetVMConfig200ResponseDataRng0 instantiates a new GetVMConfig200ResponseDataRng0 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVMConfig200ResponseDataRng0() *GetVMConfig200ResponseDataRng0 {
	this := GetVMConfig200ResponseDataRng0{}
	return &this
}

// NewGetVMConfig200ResponseDataRng0WithDefaults instantiates a new GetVMConfig200ResponseDataRng0 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVMConfig200ResponseDataRng0WithDefaults() *GetVMConfig200ResponseDataRng0 {
	this := GetVMConfig200ResponseDataRng0{}
	return &this
}

// GetMaxBytes returns the MaxBytes field value if set, zero value otherwise.
func (o *GetVMConfig200ResponseDataRng0) GetMaxBytes() int64 {
	if o == nil || IsNil(o.MaxBytes) {
		var ret int64
		return ret
	}
	return *o.MaxBytes
}

// GetMaxBytesOk returns a tuple with the MaxBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMConfig200ResponseDataRng0) GetMaxBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxBytes) {
		return nil, false
	}
	return o.MaxBytes, true
}

// HasMaxBytes returns a boolean if a field has been set.
func (o *GetVMConfig200ResponseDataRng0) HasMaxBytes() bool {
	if o != nil && !IsNil(o.MaxBytes) {
		return true
	}

	return false
}

// SetMaxBytes gets a reference to the given int64 and assigns it to the MaxBytes field.
func (o *GetVMConfig200ResponseDataRng0) SetMaxBytes(v int64) {
	o.MaxBytes = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *GetVMConfig200ResponseDataRng0) GetPeriod() int64 {
	if o == nil || IsNil(o.Period) {
		var ret int64
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMConfig200ResponseDataRng0) GetPeriodOk() (*int64, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *GetVMConfig200ResponseDataRng0) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given int64 and assigns it to the Period field.
func (o *GetVMConfig200ResponseDataRng0) SetPeriod(v int64) {
	o.Period = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *GetVMConfig200ResponseDataRng0) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMConfig200ResponseDataRng0) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *GetVMConfig200ResponseDataRng0) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *GetVMConfig200ResponseDataRng0) SetSource(v string) {
	o.Source = &v
}

func (o GetVMConfig200ResponseDataRng0) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVMConfig200ResponseDataRng0) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaxBytes) {
		toSerialize["max_bytes"] = o.MaxBytes
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	return toSerialize, nil
}

type NullableGetVMConfig200ResponseDataRng0 struct {
	value *GetVMConfig200ResponseDataRng0
	isSet bool
}

func (v NullableGetVMConfig200ResponseDataRng0) Get() *GetVMConfig200ResponseDataRng0 {
	return v.value
}

func (v *NullableGetVMConfig200ResponseDataRng0) Set(val *GetVMConfig200ResponseDataRng0) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVMConfig200ResponseDataRng0) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVMConfig200ResponseDataRng0) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVMConfig200ResponseDataRng0(val *GetVMConfig200ResponseDataRng0) *NullableGetVMConfig200ResponseDataRng0 {
	return &NullableGetVMConfig200ResponseDataRng0{value: val, isSet: true}
}

func (v NullableGetVMConfig200ResponseDataRng0) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVMConfig200ResponseDataRng0) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


