/*
ProxMox VE API

ProxMox VE API

API version: 8.0
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the GetStorage200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetStorage200ResponseDataInner{}

// GetStorage200ResponseDataInner struct for GetStorage200ResponseDataInner
type GetStorage200ResponseDataInner struct {
	Storage *string `json:"storage,omitempty"`
	Content *string `json:"content,omitempty"`
	Digest *string `json:"digest,omitempty"`
	Nodes *string `json:"nodes,omitempty"`
	Path *string `json:"path,omitempty"`
	PruneBackups *string `json:"prune-backups,omitempty"`
	Shared *bool `json:"shared,omitempty"`
	Thinpool *string `json:"thinpool,omitempty"`
	Type *string `json:"type,omitempty"`
	Vgname *string `json:"vgname,omitempty"`
}

// NewGetStorage200ResponseDataInner instantiates a new GetStorage200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStorage200ResponseDataInner() *GetStorage200ResponseDataInner {
	this := GetStorage200ResponseDataInner{}
	return &this
}

// NewGetStorage200ResponseDataInnerWithDefaults instantiates a new GetStorage200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStorage200ResponseDataInnerWithDefaults() *GetStorage200ResponseDataInner {
	this := GetStorage200ResponseDataInner{}
	return &this
}

// GetStorage returns the Storage field value if set, zero value otherwise.
func (o *GetStorage200ResponseDataInner) GetStorage() string {
	if o == nil || IsNil(o.Storage) {
		var ret string
		return ret
	}
	return *o.Storage
}

// GetStorageOk returns a tuple with the Storage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStorage200ResponseDataInner) GetStorageOk() (*string, bool) {
	if o == nil || IsNil(o.Storage) {
		return nil, false
	}
	return o.Storage, true
}

// HasStorage returns a boolean if a field has been set.
func (o *GetStorage200ResponseDataInner) HasStorage() bool {
	if o != nil && !IsNil(o.Storage) {
		return true
	}

	return false
}

// SetStorage gets a reference to the given string and assigns it to the Storage field.
func (o *GetStorage200ResponseDataInner) SetStorage(v string) {
	o.Storage = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *GetStorage200ResponseDataInner) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStorage200ResponseDataInner) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *GetStorage200ResponseDataInner) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *GetStorage200ResponseDataInner) SetContent(v string) {
	o.Content = &v
}

// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *GetStorage200ResponseDataInner) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStorage200ResponseDataInner) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *GetStorage200ResponseDataInner) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *GetStorage200ResponseDataInner) SetDigest(v string) {
	o.Digest = &v
}

// GetNodes returns the Nodes field value if set, zero value otherwise.
func (o *GetStorage200ResponseDataInner) GetNodes() string {
	if o == nil || IsNil(o.Nodes) {
		var ret string
		return ret
	}
	return *o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStorage200ResponseDataInner) GetNodesOk() (*string, bool) {
	if o == nil || IsNil(o.Nodes) {
		return nil, false
	}
	return o.Nodes, true
}

// HasNodes returns a boolean if a field has been set.
func (o *GetStorage200ResponseDataInner) HasNodes() bool {
	if o != nil && !IsNil(o.Nodes) {
		return true
	}

	return false
}

// SetNodes gets a reference to the given string and assigns it to the Nodes field.
func (o *GetStorage200ResponseDataInner) SetNodes(v string) {
	o.Nodes = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *GetStorage200ResponseDataInner) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStorage200ResponseDataInner) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *GetStorage200ResponseDataInner) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *GetStorage200ResponseDataInner) SetPath(v string) {
	o.Path = &v
}

// GetPruneBackups returns the PruneBackups field value if set, zero value otherwise.
func (o *GetStorage200ResponseDataInner) GetPruneBackups() string {
	if o == nil || IsNil(o.PruneBackups) {
		var ret string
		return ret
	}
	return *o.PruneBackups
}

// GetPruneBackupsOk returns a tuple with the PruneBackups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStorage200ResponseDataInner) GetPruneBackupsOk() (*string, bool) {
	if o == nil || IsNil(o.PruneBackups) {
		return nil, false
	}
	return o.PruneBackups, true
}

// HasPruneBackups returns a boolean if a field has been set.
func (o *GetStorage200ResponseDataInner) HasPruneBackups() bool {
	if o != nil && !IsNil(o.PruneBackups) {
		return true
	}

	return false
}

// SetPruneBackups gets a reference to the given string and assigns it to the PruneBackups field.
func (o *GetStorage200ResponseDataInner) SetPruneBackups(v string) {
	o.PruneBackups = &v
}

// GetShared returns the Shared field value if set, zero value otherwise.
func (o *GetStorage200ResponseDataInner) GetShared() bool {
	if o == nil || IsNil(o.Shared) {
		var ret bool
		return ret
	}
	return *o.Shared
}

// GetSharedOk returns a tuple with the Shared field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStorage200ResponseDataInner) GetSharedOk() (*bool, bool) {
	if o == nil || IsNil(o.Shared) {
		return nil, false
	}
	return o.Shared, true
}

// HasShared returns a boolean if a field has been set.
func (o *GetStorage200ResponseDataInner) HasShared() bool {
	if o != nil && !IsNil(o.Shared) {
		return true
	}

	return false
}

// SetShared gets a reference to the given bool and assigns it to the Shared field.
func (o *GetStorage200ResponseDataInner) SetShared(v bool) {
	o.Shared = &v
}

// GetThinpool returns the Thinpool field value if set, zero value otherwise.
func (o *GetStorage200ResponseDataInner) GetThinpool() string {
	if o == nil || IsNil(o.Thinpool) {
		var ret string
		return ret
	}
	return *o.Thinpool
}

// GetThinpoolOk returns a tuple with the Thinpool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStorage200ResponseDataInner) GetThinpoolOk() (*string, bool) {
	if o == nil || IsNil(o.Thinpool) {
		return nil, false
	}
	return o.Thinpool, true
}

// HasThinpool returns a boolean if a field has been set.
func (o *GetStorage200ResponseDataInner) HasThinpool() bool {
	if o != nil && !IsNil(o.Thinpool) {
		return true
	}

	return false
}

// SetThinpool gets a reference to the given string and assigns it to the Thinpool field.
func (o *GetStorage200ResponseDataInner) SetThinpool(v string) {
	o.Thinpool = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetStorage200ResponseDataInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStorage200ResponseDataInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetStorage200ResponseDataInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetStorage200ResponseDataInner) SetType(v string) {
	o.Type = &v
}

// GetVgname returns the Vgname field value if set, zero value otherwise.
func (o *GetStorage200ResponseDataInner) GetVgname() string {
	if o == nil || IsNil(o.Vgname) {
		var ret string
		return ret
	}
	return *o.Vgname
}

// GetVgnameOk returns a tuple with the Vgname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStorage200ResponseDataInner) GetVgnameOk() (*string, bool) {
	if o == nil || IsNil(o.Vgname) {
		return nil, false
	}
	return o.Vgname, true
}

// HasVgname returns a boolean if a field has been set.
func (o *GetStorage200ResponseDataInner) HasVgname() bool {
	if o != nil && !IsNil(o.Vgname) {
		return true
	}

	return false
}

// SetVgname gets a reference to the given string and assigns it to the Vgname field.
func (o *GetStorage200ResponseDataInner) SetVgname(v string) {
	o.Vgname = &v
}

func (o GetStorage200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetStorage200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Storage) {
		toSerialize["storage"] = o.Storage
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	if !IsNil(o.Nodes) {
		toSerialize["nodes"] = o.Nodes
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.PruneBackups) {
		toSerialize["prune-backups"] = o.PruneBackups
	}
	if !IsNil(o.Shared) {
		toSerialize["shared"] = o.Shared
	}
	if !IsNil(o.Thinpool) {
		toSerialize["thinpool"] = o.Thinpool
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Vgname) {
		toSerialize["vgname"] = o.Vgname
	}
	return toSerialize, nil
}

type NullableGetStorage200ResponseDataInner struct {
	value *GetStorage200ResponseDataInner
	isSet bool
}

func (v NullableGetStorage200ResponseDataInner) Get() *GetStorage200ResponseDataInner {
	return v.value
}

func (v *NullableGetStorage200ResponseDataInner) Set(val *GetStorage200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStorage200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStorage200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStorage200ResponseDataInner(val *GetStorage200ResponseDataInner) *NullableGetStorage200ResponseDataInner {
	return &NullableGetStorage200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetStorage200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStorage200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


