/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the CreateContainerRequestUnused0 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateContainerRequestUnused0{}

// CreateContainerRequestUnused0 struct for CreateContainerRequestUnused0
type CreateContainerRequestUnused0 struct {
	Volume string `json:"volume"`
}

// NewCreateContainerRequestUnused0 instantiates a new CreateContainerRequestUnused0 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateContainerRequestUnused0(volume string) *CreateContainerRequestUnused0 {
	this := CreateContainerRequestUnused0{}
	this.Volume = volume
	return &this
}

// NewCreateContainerRequestUnused0WithDefaults instantiates a new CreateContainerRequestUnused0 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateContainerRequestUnused0WithDefaults() *CreateContainerRequestUnused0 {
	this := CreateContainerRequestUnused0{}
	return &this
}

// GetVolume returns the Volume field value
func (o *CreateContainerRequestUnused0) GetVolume() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value
// and a boolean to check if the value has been set.
func (o *CreateContainerRequestUnused0) GetVolumeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Volume, true
}

// SetVolume sets field value
func (o *CreateContainerRequestUnused0) SetVolume(v string) {
	o.Volume = v
}

func (o CreateContainerRequestUnused0) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateContainerRequestUnused0) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["volume"] = o.Volume
	return toSerialize, nil
}

type NullableCreateContainerRequestUnused0 struct {
	value *CreateContainerRequestUnused0
	isSet bool
}

func (v NullableCreateContainerRequestUnused0) Get() *CreateContainerRequestUnused0 {
	return v.value
}

func (v *NullableCreateContainerRequestUnused0) Set(val *CreateContainerRequestUnused0) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateContainerRequestUnused0) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateContainerRequestUnused0) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateContainerRequestUnused0(val *CreateContainerRequestUnused0) *NullableCreateContainerRequestUnused0 {
	return &NullableCreateContainerRequestUnused0{value: val, isSet: true}
}

func (v NullableCreateContainerRequestUnused0) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateContainerRequestUnused0) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


