/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the CreateVMRequestSpiceEnhancements type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVMRequestSpiceEnhancements{}

// CreateVMRequestSpiceEnhancements struct for CreateVMRequestSpiceEnhancements
type CreateVMRequestSpiceEnhancements struct {
	Foldersharing *bool `json:"foldersharing,omitempty"`
	Videostreaming *string `json:"videostreaming,omitempty"`
}

// NewCreateVMRequestSpiceEnhancements instantiates a new CreateVMRequestSpiceEnhancements object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVMRequestSpiceEnhancements() *CreateVMRequestSpiceEnhancements {
	this := CreateVMRequestSpiceEnhancements{}
	return &this
}

// NewCreateVMRequestSpiceEnhancementsWithDefaults instantiates a new CreateVMRequestSpiceEnhancements object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVMRequestSpiceEnhancementsWithDefaults() *CreateVMRequestSpiceEnhancements {
	this := CreateVMRequestSpiceEnhancements{}
	return &this
}

// GetFoldersharing returns the Foldersharing field value if set, zero value otherwise.
func (o *CreateVMRequestSpiceEnhancements) GetFoldersharing() bool {
	if o == nil || IsNil(o.Foldersharing) {
		var ret bool
		return ret
	}
	return *o.Foldersharing
}

// GetFoldersharingOk returns a tuple with the Foldersharing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSpiceEnhancements) GetFoldersharingOk() (*bool, bool) {
	if o == nil || IsNil(o.Foldersharing) {
		return nil, false
	}
	return o.Foldersharing, true
}

// HasFoldersharing returns a boolean if a field has been set.
func (o *CreateVMRequestSpiceEnhancements) HasFoldersharing() bool {
	if o != nil && !IsNil(o.Foldersharing) {
		return true
	}

	return false
}

// SetFoldersharing gets a reference to the given bool and assigns it to the Foldersharing field.
func (o *CreateVMRequestSpiceEnhancements) SetFoldersharing(v bool) {
	o.Foldersharing = &v
}

// GetVideostreaming returns the Videostreaming field value if set, zero value otherwise.
func (o *CreateVMRequestSpiceEnhancements) GetVideostreaming() string {
	if o == nil || IsNil(o.Videostreaming) {
		var ret string
		return ret
	}
	return *o.Videostreaming
}

// GetVideostreamingOk returns a tuple with the Videostreaming field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestSpiceEnhancements) GetVideostreamingOk() (*string, bool) {
	if o == nil || IsNil(o.Videostreaming) {
		return nil, false
	}
	return o.Videostreaming, true
}

// HasVideostreaming returns a boolean if a field has been set.
func (o *CreateVMRequestSpiceEnhancements) HasVideostreaming() bool {
	if o != nil && !IsNil(o.Videostreaming) {
		return true
	}

	return false
}

// SetVideostreaming gets a reference to the given string and assigns it to the Videostreaming field.
func (o *CreateVMRequestSpiceEnhancements) SetVideostreaming(v string) {
	o.Videostreaming = &v
}

func (o CreateVMRequestSpiceEnhancements) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVMRequestSpiceEnhancements) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Foldersharing) {
		toSerialize["foldersharing"] = o.Foldersharing
	}
	if !IsNil(o.Videostreaming) {
		toSerialize["videostreaming"] = o.Videostreaming
	}
	return toSerialize, nil
}

type NullableCreateVMRequestSpiceEnhancements struct {
	value *CreateVMRequestSpiceEnhancements
	isSet bool
}

func (v NullableCreateVMRequestSpiceEnhancements) Get() *CreateVMRequestSpiceEnhancements {
	return v.value
}

func (v *NullableCreateVMRequestSpiceEnhancements) Set(val *CreateVMRequestSpiceEnhancements) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVMRequestSpiceEnhancements) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVMRequestSpiceEnhancements) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVMRequestSpiceEnhancements(val *CreateVMRequestSpiceEnhancements) *NullableCreateVMRequestSpiceEnhancements {
	return &NullableCreateVMRequestSpiceEnhancements{value: val, isSet: true}
}

func (v NullableCreateVMRequestSpiceEnhancements) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVMRequestSpiceEnhancements) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


