/*
ProxMox VE API

ProxMox VE API

API version: 8.0
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the GetVMConfig200ResponseDataMemory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVMConfig200ResponseDataMemory{}

// GetVMConfig200ResponseDataMemory struct for GetVMConfig200ResponseDataMemory
type GetVMConfig200ResponseDataMemory struct {
	// Current amount of online RAM for the VM in MiB. This is the maximum available memory when you use the balloon device.
	Current *int64 `json:"current,omitempty"`
}

// NewGetVMConfig200ResponseDataMemory instantiates a new GetVMConfig200ResponseDataMemory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVMConfig200ResponseDataMemory() *GetVMConfig200ResponseDataMemory {
	this := GetVMConfig200ResponseDataMemory{}
	return &this
}

// NewGetVMConfig200ResponseDataMemoryWithDefaults instantiates a new GetVMConfig200ResponseDataMemory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVMConfig200ResponseDataMemoryWithDefaults() *GetVMConfig200ResponseDataMemory {
	this := GetVMConfig200ResponseDataMemory{}
	return &this
}

// GetCurrent returns the Current field value if set, zero value otherwise.
func (o *GetVMConfig200ResponseDataMemory) GetCurrent() int64 {
	if o == nil || IsNil(o.Current) {
		var ret int64
		return ret
	}
	return *o.Current
}

// GetCurrentOk returns a tuple with the Current field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMConfig200ResponseDataMemory) GetCurrentOk() (*int64, bool) {
	if o == nil || IsNil(o.Current) {
		return nil, false
	}
	return o.Current, true
}

// HasCurrent returns a boolean if a field has been set.
func (o *GetVMConfig200ResponseDataMemory) HasCurrent() bool {
	if o != nil && !IsNil(o.Current) {
		return true
	}

	return false
}

// SetCurrent gets a reference to the given int64 and assigns it to the Current field.
func (o *GetVMConfig200ResponseDataMemory) SetCurrent(v int64) {
	o.Current = &v
}

func (o GetVMConfig200ResponseDataMemory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVMConfig200ResponseDataMemory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Current) {
		toSerialize["current"] = o.Current
	}
	return toSerialize, nil
}

type NullableGetVMConfig200ResponseDataMemory struct {
	value *GetVMConfig200ResponseDataMemory
	isSet bool
}

func (v NullableGetVMConfig200ResponseDataMemory) Get() *GetVMConfig200ResponseDataMemory {
	return v.value
}

func (v *NullableGetVMConfig200ResponseDataMemory) Set(val *GetVMConfig200ResponseDataMemory) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVMConfig200ResponseDataMemory) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVMConfig200ResponseDataMemory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVMConfig200ResponseDataMemory(val *GetVMConfig200ResponseDataMemory) *NullableGetVMConfig200ResponseDataMemory {
	return &NullableGetVMConfig200ResponseDataMemory{value: val, isSet: true}
}

func (v NullableGetVMConfig200ResponseDataMemory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVMConfig200ResponseDataMemory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


