/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the GetContainerConfig200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetContainerConfig200Response{}

// GetContainerConfig200Response struct for GetContainerConfig200Response
type GetContainerConfig200Response struct {
	Data *GetContainerConfig200ResponseData `json:"data,omitempty"`
	Errors []string `json:"errors,omitempty"`
}

// NewGetContainerConfig200Response instantiates a new GetContainerConfig200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetContainerConfig200Response() *GetContainerConfig200Response {
	this := GetContainerConfig200Response{}
	return &this
}

// NewGetContainerConfig200ResponseWithDefaults instantiates a new GetContainerConfig200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetContainerConfig200ResponseWithDefaults() *GetContainerConfig200Response {
	this := GetContainerConfig200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetContainerConfig200Response) GetData() GetContainerConfig200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret GetContainerConfig200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContainerConfig200Response) GetDataOk() (*GetContainerConfig200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetContainerConfig200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GetContainerConfig200ResponseData and assigns it to the Data field.
func (o *GetContainerConfig200Response) SetData(v GetContainerConfig200ResponseData) {
	o.Data = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *GetContainerConfig200Response) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContainerConfig200Response) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *GetContainerConfig200Response) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *GetContainerConfig200Response) SetErrors(v []string) {
	o.Errors = v
}

func (o GetContainerConfig200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetContainerConfig200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableGetContainerConfig200Response struct {
	value *GetContainerConfig200Response
	isSet bool
}

func (v NullableGetContainerConfig200Response) Get() *GetContainerConfig200Response {
	return v.value
}

func (v *NullableGetContainerConfig200Response) Set(val *GetContainerConfig200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetContainerConfig200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetContainerConfig200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetContainerConfig200Response(val *GetContainerConfig200Response) *NullableGetContainerConfig200Response {
	return &NullableGetContainerConfig200Response{value: val, isSet: true}
}

func (v NullableGetContainerConfig200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetContainerConfig200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


