/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the GetClusterNextid200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetClusterNextid200Response{}

// GetClusterNextid200Response struct for GetClusterNextid200Response
type GetClusterNextid200Response struct {
	// The next free VMID.
	Data *string `json:"data,omitempty"`
	Errors []string `json:"errors,omitempty"`
}

// NewGetClusterNextid200Response instantiates a new GetClusterNextid200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClusterNextid200Response() *GetClusterNextid200Response {
	this := GetClusterNextid200Response{}
	return &this
}

// NewGetClusterNextid200ResponseWithDefaults instantiates a new GetClusterNextid200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClusterNextid200ResponseWithDefaults() *GetClusterNextid200Response {
	this := GetClusterNextid200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetClusterNextid200Response) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetClusterNextid200Response) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetClusterNextid200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *GetClusterNextid200Response) SetData(v string) {
	o.Data = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *GetClusterNextid200Response) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetClusterNextid200Response) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *GetClusterNextid200Response) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *GetClusterNextid200Response) SetErrors(v []string) {
	o.Errors = v
}

func (o GetClusterNextid200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetClusterNextid200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableGetClusterNextid200Response struct {
	value *GetClusterNextid200Response
	isSet bool
}

func (v NullableGetClusterNextid200Response) Get() *GetClusterNextid200Response {
	return v.value
}

func (v *NullableGetClusterNextid200Response) Set(val *GetClusterNextid200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClusterNextid200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClusterNextid200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClusterNextid200Response(val *GetClusterNextid200Response) *NullableGetClusterNextid200Response {
	return &NullableGetClusterNextid200Response{value: val, isSet: true}
}

func (v NullableGetClusterNextid200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClusterNextid200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


