/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the CreateVMRequestRng0 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVMRequestRng0{}

// CreateVMRequestRng0 struct for CreateVMRequestRng0
type CreateVMRequestRng0 struct {
	MaxBytes *int64 `json:"max_bytes,omitempty"`
	Period *int64 `json:"period,omitempty"`
	Source string `json:"source"`
}

// NewCreateVMRequestRng0 instantiates a new CreateVMRequestRng0 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVMRequestRng0(source string) *CreateVMRequestRng0 {
	this := CreateVMRequestRng0{}
	this.Source = source
	return &this
}

// NewCreateVMRequestRng0WithDefaults instantiates a new CreateVMRequestRng0 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVMRequestRng0WithDefaults() *CreateVMRequestRng0 {
	this := CreateVMRequestRng0{}
	return &this
}

// GetMaxBytes returns the MaxBytes field value if set, zero value otherwise.
func (o *CreateVMRequestRng0) GetMaxBytes() int64 {
	if o == nil || IsNil(o.MaxBytes) {
		var ret int64
		return ret
	}
	return *o.MaxBytes
}

// GetMaxBytesOk returns a tuple with the MaxBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestRng0) GetMaxBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxBytes) {
		return nil, false
	}
	return o.MaxBytes, true
}

// HasMaxBytes returns a boolean if a field has been set.
func (o *CreateVMRequestRng0) HasMaxBytes() bool {
	if o != nil && !IsNil(o.MaxBytes) {
		return true
	}

	return false
}

// SetMaxBytes gets a reference to the given int64 and assigns it to the MaxBytes field.
func (o *CreateVMRequestRng0) SetMaxBytes(v int64) {
	o.MaxBytes = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *CreateVMRequestRng0) GetPeriod() int64 {
	if o == nil || IsNil(o.Period) {
		var ret int64
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestRng0) GetPeriodOk() (*int64, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *CreateVMRequestRng0) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given int64 and assigns it to the Period field.
func (o *CreateVMRequestRng0) SetPeriod(v int64) {
	o.Period = &v
}

// GetSource returns the Source field value
func (o *CreateVMRequestRng0) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *CreateVMRequestRng0) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *CreateVMRequestRng0) SetSource(v string) {
	o.Source = v
}

func (o CreateVMRequestRng0) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVMRequestRng0) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaxBytes) {
		toSerialize["max_bytes"] = o.MaxBytes
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

type NullableCreateVMRequestRng0 struct {
	value *CreateVMRequestRng0
	isSet bool
}

func (v NullableCreateVMRequestRng0) Get() *CreateVMRequestRng0 {
	return v.value
}

func (v *NullableCreateVMRequestRng0) Set(val *CreateVMRequestRng0) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVMRequestRng0) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVMRequestRng0) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVMRequestRng0(val *CreateVMRequestRng0) *NullableCreateVMRequestRng0 {
	return &NullableCreateVMRequestRng0{value: val, isSet: true}
}

func (v NullableCreateVMRequestRng0) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVMRequestRng0) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


