/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the RebootVMRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RebootVMRequest{}

// RebootVMRequest struct for RebootVMRequest
type RebootVMRequest struct {
	// Wait maximal timeout seconds for the shutdown.
	Timeout *int64 `json:"timeout,omitempty"`
}

// NewRebootVMRequest instantiates a new RebootVMRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRebootVMRequest() *RebootVMRequest {
	this := RebootVMRequest{}
	return &this
}

// NewRebootVMRequestWithDefaults instantiates a new RebootVMRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRebootVMRequestWithDefaults() *RebootVMRequest {
	this := RebootVMRequest{}
	return &this
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *RebootVMRequest) GetTimeout() int64 {
	if o == nil || IsNil(o.Timeout) {
		var ret int64
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RebootVMRequest) GetTimeoutOk() (*int64, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *RebootVMRequest) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int64 and assigns it to the Timeout field.
func (o *RebootVMRequest) SetTimeout(v int64) {
	o.Timeout = &v
}

func (o RebootVMRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RebootVMRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	return toSerialize, nil
}

type NullableRebootVMRequest struct {
	value *RebootVMRequest
	isSet bool
}

func (v NullableRebootVMRequest) Get() *RebootVMRequest {
	return v.value
}

func (v *NullableRebootVMRequest) Set(val *RebootVMRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRebootVMRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRebootVMRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRebootVMRequest(val *RebootVMRequest) *NullableRebootVMRequest {
	return &NullableRebootVMRequest{value: val, isSet: true}
}

func (v NullableRebootVMRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRebootVMRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


