/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the UpdateVMSnapshotConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateVMSnapshotConfigRequest{}

// UpdateVMSnapshotConfigRequest struct for UpdateVMSnapshotConfigRequest
type UpdateVMSnapshotConfigRequest struct {
	Description *string `json:"description,omitempty"`
}

// NewUpdateVMSnapshotConfigRequest instantiates a new UpdateVMSnapshotConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateVMSnapshotConfigRequest() *UpdateVMSnapshotConfigRequest {
	this := UpdateVMSnapshotConfigRequest{}
	return &this
}

// NewUpdateVMSnapshotConfigRequestWithDefaults instantiates a new UpdateVMSnapshotConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateVMSnapshotConfigRequestWithDefaults() *UpdateVMSnapshotConfigRequest {
	this := UpdateVMSnapshotConfigRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateVMSnapshotConfigRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateVMSnapshotConfigRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateVMSnapshotConfigRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateVMSnapshotConfigRequest) SetDescription(v string) {
	o.Description = &v
}

func (o UpdateVMSnapshotConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateVMSnapshotConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableUpdateVMSnapshotConfigRequest struct {
	value *UpdateVMSnapshotConfigRequest
	isSet bool
}

func (v NullableUpdateVMSnapshotConfigRequest) Get() *UpdateVMSnapshotConfigRequest {
	return v.value
}

func (v *NullableUpdateVMSnapshotConfigRequest) Set(val *UpdateVMSnapshotConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateVMSnapshotConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateVMSnapshotConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateVMSnapshotConfigRequest(val *UpdateVMSnapshotConfigRequest) *NullableUpdateVMSnapshotConfigRequest {
	return &NullableUpdateVMSnapshotConfigRequest{value: val, isSet: true}
}

func (v NullableUpdateVMSnapshotConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateVMSnapshotConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


