/*
ProxMox VE API

ProxMox VE API

API version: 8.0
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the GetVMConfig200ResponseDataBoot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVMConfig200ResponseDataBoot{}

// GetVMConfig200ResponseDataBoot struct for GetVMConfig200ResponseDataBoot
type GetVMConfig200ResponseDataBoot struct {
	// order
	Order *string `json:"order,omitempty"`
}

// NewGetVMConfig200ResponseDataBoot instantiates a new GetVMConfig200ResponseDataBoot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVMConfig200ResponseDataBoot() *GetVMConfig200ResponseDataBoot {
	this := GetVMConfig200ResponseDataBoot{}
	return &this
}

// NewGetVMConfig200ResponseDataBootWithDefaults instantiates a new GetVMConfig200ResponseDataBoot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVMConfig200ResponseDataBootWithDefaults() *GetVMConfig200ResponseDataBoot {
	this := GetVMConfig200ResponseDataBoot{}
	return &this
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *GetVMConfig200ResponseDataBoot) GetOrder() string {
	if o == nil || IsNil(o.Order) {
		var ret string
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMConfig200ResponseDataBoot) GetOrderOk() (*string, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *GetVMConfig200ResponseDataBoot) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given string and assigns it to the Order field.
func (o *GetVMConfig200ResponseDataBoot) SetOrder(v string) {
	o.Order = &v
}

func (o GetVMConfig200ResponseDataBoot) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVMConfig200ResponseDataBoot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	return toSerialize, nil
}

type NullableGetVMConfig200ResponseDataBoot struct {
	value *GetVMConfig200ResponseDataBoot
	isSet bool
}

func (v NullableGetVMConfig200ResponseDataBoot) Get() *GetVMConfig200ResponseDataBoot {
	return v.value
}

func (v *NullableGetVMConfig200ResponseDataBoot) Set(val *GetVMConfig200ResponseDataBoot) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVMConfig200ResponseDataBoot) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVMConfig200ResponseDataBoot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVMConfig200ResponseDataBoot(val *GetVMConfig200ResponseDataBoot) *NullableGetVMConfig200ResponseDataBoot {
	return &NullableGetVMConfig200ResponseDataBoot{value: val, isSet: true}
}

func (v NullableGetVMConfig200ResponseDataBoot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVMConfig200ResponseDataBoot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


