/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the CreateVMRequestWatchdog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVMRequestWatchdog{}

// CreateVMRequestWatchdog struct for CreateVMRequestWatchdog
type CreateVMRequestWatchdog struct {
	Action *string `json:"action,omitempty"`
	Model *string `json:"model,omitempty"`
}

// NewCreateVMRequestWatchdog instantiates a new CreateVMRequestWatchdog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVMRequestWatchdog() *CreateVMRequestWatchdog {
	this := CreateVMRequestWatchdog{}
	return &this
}

// NewCreateVMRequestWatchdogWithDefaults instantiates a new CreateVMRequestWatchdog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVMRequestWatchdogWithDefaults() *CreateVMRequestWatchdog {
	this := CreateVMRequestWatchdog{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *CreateVMRequestWatchdog) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestWatchdog) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *CreateVMRequestWatchdog) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *CreateVMRequestWatchdog) SetAction(v string) {
	o.Action = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *CreateVMRequestWatchdog) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestWatchdog) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *CreateVMRequestWatchdog) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *CreateVMRequestWatchdog) SetModel(v string) {
	o.Model = &v
}

func (o CreateVMRequestWatchdog) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVMRequestWatchdog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	return toSerialize, nil
}

type NullableCreateVMRequestWatchdog struct {
	value *CreateVMRequestWatchdog
	isSet bool
}

func (v NullableCreateVMRequestWatchdog) Get() *CreateVMRequestWatchdog {
	return v.value
}

func (v *NullableCreateVMRequestWatchdog) Set(val *CreateVMRequestWatchdog) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVMRequestWatchdog) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVMRequestWatchdog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVMRequestWatchdog(val *CreateVMRequestWatchdog) *NullableCreateVMRequestWatchdog {
	return &NullableCreateVMRequestWatchdog{value: val, isSet: true}
}

func (v NullableCreateVMRequestWatchdog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVMRequestWatchdog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


