/*
ProxMox VE API

ProxMox VE API

API version: 8.0
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the GetVMs200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVMs200ResponseDataInner{}

// GetVMs200ResponseDataInner struct for GetVMs200ResponseDataInner
type GetVMs200ResponseDataInner struct {
	// Maximum usable CPUs.
	Cpus *float32 `json:"cpus,omitempty"`
	// The current config lock, if any.
	Lock *string `json:"lock,omitempty"`
	// Root disk size in bytes.
	Maxdisk *int64 `json:"maxdisk,omitempty"`
	// Maximum memory in bytes.
	Maxmem *int64 `json:"maxmem,omitempty"`
	// VM name.
	Name *string `json:"name,omitempty"`
	// PID of running qemu process.
	Pid *int64 `json:"pid,omitempty"`
	// VM run state from the 'query-status' QMP monitor command.
	Qmpstatus *string `json:"qmpstatus,omitempty"`
	// The currently running machine type (if running).
	RunningMachine *string `json:"running-machine,omitempty"`
	// The currently running QEMU version (if running).
	RunningQemu *string `json:"running-qemu,omitempty"`
	// QEMU process status.
	Status *string `json:"status,omitempty"`
	// The current configured tags, if any
	Tags *string `json:"tags,omitempty"`
	// Uptime.
	Uptime *int64 `json:"uptime,omitempty"`
	// The (unique) ID of the VM.
	Vmid *int64 `json:"vmid,omitempty"`
}

// NewGetVMs200ResponseDataInner instantiates a new GetVMs200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVMs200ResponseDataInner() *GetVMs200ResponseDataInner {
	this := GetVMs200ResponseDataInner{}
	return &this
}

// NewGetVMs200ResponseDataInnerWithDefaults instantiates a new GetVMs200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVMs200ResponseDataInnerWithDefaults() *GetVMs200ResponseDataInner {
	this := GetVMs200ResponseDataInner{}
	return &this
}

// GetCpus returns the Cpus field value if set, zero value otherwise.
func (o *GetVMs200ResponseDataInner) GetCpus() float32 {
	if o == nil || IsNil(o.Cpus) {
		var ret float32
		return ret
	}
	return *o.Cpus
}

// GetCpusOk returns a tuple with the Cpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMs200ResponseDataInner) GetCpusOk() (*float32, bool) {
	if o == nil || IsNil(o.Cpus) {
		return nil, false
	}
	return o.Cpus, true
}

// HasCpus returns a boolean if a field has been set.
func (o *GetVMs200ResponseDataInner) HasCpus() bool {
	if o != nil && !IsNil(o.Cpus) {
		return true
	}

	return false
}

// SetCpus gets a reference to the given float32 and assigns it to the Cpus field.
func (o *GetVMs200ResponseDataInner) SetCpus(v float32) {
	o.Cpus = &v
}

// GetLock returns the Lock field value if set, zero value otherwise.
func (o *GetVMs200ResponseDataInner) GetLock() string {
	if o == nil || IsNil(o.Lock) {
		var ret string
		return ret
	}
	return *o.Lock
}

// GetLockOk returns a tuple with the Lock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMs200ResponseDataInner) GetLockOk() (*string, bool) {
	if o == nil || IsNil(o.Lock) {
		return nil, false
	}
	return o.Lock, true
}

// HasLock returns a boolean if a field has been set.
func (o *GetVMs200ResponseDataInner) HasLock() bool {
	if o != nil && !IsNil(o.Lock) {
		return true
	}

	return false
}

// SetLock gets a reference to the given string and assigns it to the Lock field.
func (o *GetVMs200ResponseDataInner) SetLock(v string) {
	o.Lock = &v
}

// GetMaxdisk returns the Maxdisk field value if set, zero value otherwise.
func (o *GetVMs200ResponseDataInner) GetMaxdisk() int64 {
	if o == nil || IsNil(o.Maxdisk) {
		var ret int64
		return ret
	}
	return *o.Maxdisk
}

// GetMaxdiskOk returns a tuple with the Maxdisk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMs200ResponseDataInner) GetMaxdiskOk() (*int64, bool) {
	if o == nil || IsNil(o.Maxdisk) {
		return nil, false
	}
	return o.Maxdisk, true
}

// HasMaxdisk returns a boolean if a field has been set.
func (o *GetVMs200ResponseDataInner) HasMaxdisk() bool {
	if o != nil && !IsNil(o.Maxdisk) {
		return true
	}

	return false
}

// SetMaxdisk gets a reference to the given int64 and assigns it to the Maxdisk field.
func (o *GetVMs200ResponseDataInner) SetMaxdisk(v int64) {
	o.Maxdisk = &v
}

// GetMaxmem returns the Maxmem field value if set, zero value otherwise.
func (o *GetVMs200ResponseDataInner) GetMaxmem() int64 {
	if o == nil || IsNil(o.Maxmem) {
		var ret int64
		return ret
	}
	return *o.Maxmem
}

// GetMaxmemOk returns a tuple with the Maxmem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMs200ResponseDataInner) GetMaxmemOk() (*int64, bool) {
	if o == nil || IsNil(o.Maxmem) {
		return nil, false
	}
	return o.Maxmem, true
}

// HasMaxmem returns a boolean if a field has been set.
func (o *GetVMs200ResponseDataInner) HasMaxmem() bool {
	if o != nil && !IsNil(o.Maxmem) {
		return true
	}

	return false
}

// SetMaxmem gets a reference to the given int64 and assigns it to the Maxmem field.
func (o *GetVMs200ResponseDataInner) SetMaxmem(v int64) {
	o.Maxmem = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetVMs200ResponseDataInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMs200ResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetVMs200ResponseDataInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetVMs200ResponseDataInner) SetName(v string) {
	o.Name = &v
}

// GetPid returns the Pid field value if set, zero value otherwise.
func (o *GetVMs200ResponseDataInner) GetPid() int64 {
	if o == nil || IsNil(o.Pid) {
		var ret int64
		return ret
	}
	return *o.Pid
}

// GetPidOk returns a tuple with the Pid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMs200ResponseDataInner) GetPidOk() (*int64, bool) {
	if o == nil || IsNil(o.Pid) {
		return nil, false
	}
	return o.Pid, true
}

// HasPid returns a boolean if a field has been set.
func (o *GetVMs200ResponseDataInner) HasPid() bool {
	if o != nil && !IsNil(o.Pid) {
		return true
	}

	return false
}

// SetPid gets a reference to the given int64 and assigns it to the Pid field.
func (o *GetVMs200ResponseDataInner) SetPid(v int64) {
	o.Pid = &v
}

// GetQmpstatus returns the Qmpstatus field value if set, zero value otherwise.
func (o *GetVMs200ResponseDataInner) GetQmpstatus() string {
	if o == nil || IsNil(o.Qmpstatus) {
		var ret string
		return ret
	}
	return *o.Qmpstatus
}

// GetQmpstatusOk returns a tuple with the Qmpstatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMs200ResponseDataInner) GetQmpstatusOk() (*string, bool) {
	if o == nil || IsNil(o.Qmpstatus) {
		return nil, false
	}
	return o.Qmpstatus, true
}

// HasQmpstatus returns a boolean if a field has been set.
func (o *GetVMs200ResponseDataInner) HasQmpstatus() bool {
	if o != nil && !IsNil(o.Qmpstatus) {
		return true
	}

	return false
}

// SetQmpstatus gets a reference to the given string and assigns it to the Qmpstatus field.
func (o *GetVMs200ResponseDataInner) SetQmpstatus(v string) {
	o.Qmpstatus = &v
}

// GetRunningMachine returns the RunningMachine field value if set, zero value otherwise.
func (o *GetVMs200ResponseDataInner) GetRunningMachine() string {
	if o == nil || IsNil(o.RunningMachine) {
		var ret string
		return ret
	}
	return *o.RunningMachine
}

// GetRunningMachineOk returns a tuple with the RunningMachine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMs200ResponseDataInner) GetRunningMachineOk() (*string, bool) {
	if o == nil || IsNil(o.RunningMachine) {
		return nil, false
	}
	return o.RunningMachine, true
}

// HasRunningMachine returns a boolean if a field has been set.
func (o *GetVMs200ResponseDataInner) HasRunningMachine() bool {
	if o != nil && !IsNil(o.RunningMachine) {
		return true
	}

	return false
}

// SetRunningMachine gets a reference to the given string and assigns it to the RunningMachine field.
func (o *GetVMs200ResponseDataInner) SetRunningMachine(v string) {
	o.RunningMachine = &v
}

// GetRunningQemu returns the RunningQemu field value if set, zero value otherwise.
func (o *GetVMs200ResponseDataInner) GetRunningQemu() string {
	if o == nil || IsNil(o.RunningQemu) {
		var ret string
		return ret
	}
	return *o.RunningQemu
}

// GetRunningQemuOk returns a tuple with the RunningQemu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMs200ResponseDataInner) GetRunningQemuOk() (*string, bool) {
	if o == nil || IsNil(o.RunningQemu) {
		return nil, false
	}
	return o.RunningQemu, true
}

// HasRunningQemu returns a boolean if a field has been set.
func (o *GetVMs200ResponseDataInner) HasRunningQemu() bool {
	if o != nil && !IsNil(o.RunningQemu) {
		return true
	}

	return false
}

// SetRunningQemu gets a reference to the given string and assigns it to the RunningQemu field.
func (o *GetVMs200ResponseDataInner) SetRunningQemu(v string) {
	o.RunningQemu = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetVMs200ResponseDataInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMs200ResponseDataInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetVMs200ResponseDataInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetVMs200ResponseDataInner) SetStatus(v string) {
	o.Status = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *GetVMs200ResponseDataInner) GetTags() string {
	if o == nil || IsNil(o.Tags) {
		var ret string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMs200ResponseDataInner) GetTagsOk() (*string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *GetVMs200ResponseDataInner) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given string and assigns it to the Tags field.
func (o *GetVMs200ResponseDataInner) SetTags(v string) {
	o.Tags = &v
}

// GetUptime returns the Uptime field value if set, zero value otherwise.
func (o *GetVMs200ResponseDataInner) GetUptime() int64 {
	if o == nil || IsNil(o.Uptime) {
		var ret int64
		return ret
	}
	return *o.Uptime
}

// GetUptimeOk returns a tuple with the Uptime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMs200ResponseDataInner) GetUptimeOk() (*int64, bool) {
	if o == nil || IsNil(o.Uptime) {
		return nil, false
	}
	return o.Uptime, true
}

// HasUptime returns a boolean if a field has been set.
func (o *GetVMs200ResponseDataInner) HasUptime() bool {
	if o != nil && !IsNil(o.Uptime) {
		return true
	}

	return false
}

// SetUptime gets a reference to the given int64 and assigns it to the Uptime field.
func (o *GetVMs200ResponseDataInner) SetUptime(v int64) {
	o.Uptime = &v
}

// GetVmid returns the Vmid field value if set, zero value otherwise.
func (o *GetVMs200ResponseDataInner) GetVmid() int64 {
	if o == nil || IsNil(o.Vmid) {
		var ret int64
		return ret
	}
	return *o.Vmid
}

// GetVmidOk returns a tuple with the Vmid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMs200ResponseDataInner) GetVmidOk() (*int64, bool) {
	if o == nil || IsNil(o.Vmid) {
		return nil, false
	}
	return o.Vmid, true
}

// HasVmid returns a boolean if a field has been set.
func (o *GetVMs200ResponseDataInner) HasVmid() bool {
	if o != nil && !IsNil(o.Vmid) {
		return true
	}

	return false
}

// SetVmid gets a reference to the given int64 and assigns it to the Vmid field.
func (o *GetVMs200ResponseDataInner) SetVmid(v int64) {
	o.Vmid = &v
}

func (o GetVMs200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVMs200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cpus) {
		toSerialize["cpus"] = o.Cpus
	}
	if !IsNil(o.Lock) {
		toSerialize["lock"] = o.Lock
	}
	if !IsNil(o.Maxdisk) {
		toSerialize["maxdisk"] = o.Maxdisk
	}
	if !IsNil(o.Maxmem) {
		toSerialize["maxmem"] = o.Maxmem
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Pid) {
		toSerialize["pid"] = o.Pid
	}
	if !IsNil(o.Qmpstatus) {
		toSerialize["qmpstatus"] = o.Qmpstatus
	}
	if !IsNil(o.RunningMachine) {
		toSerialize["running-machine"] = o.RunningMachine
	}
	if !IsNil(o.RunningQemu) {
		toSerialize["running-qemu"] = o.RunningQemu
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Uptime) {
		toSerialize["uptime"] = o.Uptime
	}
	if !IsNil(o.Vmid) {
		toSerialize["vmid"] = o.Vmid
	}
	return toSerialize, nil
}

type NullableGetVMs200ResponseDataInner struct {
	value *GetVMs200ResponseDataInner
	isSet bool
}

func (v NullableGetVMs200ResponseDataInner) Get() *GetVMs200ResponseDataInner {
	return v.value
}

func (v *NullableGetVMs200ResponseDataInner) Set(val *GetVMs200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVMs200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVMs200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVMs200ResponseDataInner(val *GetVMs200ResponseDataInner) *NullableGetVMs200ResponseDataInner {
	return &NullableGetVMs200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetVMs200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVMs200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


