/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the GetNodeTaskLog200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNodeTaskLog200ResponseDataInner{}

// GetNodeTaskLog200ResponseDataInner 
type GetNodeTaskLog200ResponseDataInner struct {
	// Line number
	N *int64 `json:"n,omitempty"`
	// Line text
	T *string `json:"t,omitempty"`
}

// NewGetNodeTaskLog200ResponseDataInner instantiates a new GetNodeTaskLog200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNodeTaskLog200ResponseDataInner() *GetNodeTaskLog200ResponseDataInner {
	this := GetNodeTaskLog200ResponseDataInner{}
	return &this
}

// NewGetNodeTaskLog200ResponseDataInnerWithDefaults instantiates a new GetNodeTaskLog200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNodeTaskLog200ResponseDataInnerWithDefaults() *GetNodeTaskLog200ResponseDataInner {
	this := GetNodeTaskLog200ResponseDataInner{}
	return &this
}

// GetN returns the N field value if set, zero value otherwise.
func (o *GetNodeTaskLog200ResponseDataInner) GetN() int64 {
	if o == nil || IsNil(o.N) {
		var ret int64
		return ret
	}
	return *o.N
}

// GetNOk returns a tuple with the N field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNodeTaskLog200ResponseDataInner) GetNOk() (*int64, bool) {
	if o == nil || IsNil(o.N) {
		return nil, false
	}
	return o.N, true
}

// HasN returns a boolean if a field has been set.
func (o *GetNodeTaskLog200ResponseDataInner) HasN() bool {
	if o != nil && !IsNil(o.N) {
		return true
	}

	return false
}

// SetN gets a reference to the given int64 and assigns it to the N field.
func (o *GetNodeTaskLog200ResponseDataInner) SetN(v int64) {
	o.N = &v
}

// GetT returns the T field value if set, zero value otherwise.
func (o *GetNodeTaskLog200ResponseDataInner) GetT() string {
	if o == nil || IsNil(o.T) {
		var ret string
		return ret
	}
	return *o.T
}

// GetTOk returns a tuple with the T field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNodeTaskLog200ResponseDataInner) GetTOk() (*string, bool) {
	if o == nil || IsNil(o.T) {
		return nil, false
	}
	return o.T, true
}

// HasT returns a boolean if a field has been set.
func (o *GetNodeTaskLog200ResponseDataInner) HasT() bool {
	if o != nil && !IsNil(o.T) {
		return true
	}

	return false
}

// SetT gets a reference to the given string and assigns it to the T field.
func (o *GetNodeTaskLog200ResponseDataInner) SetT(v string) {
	o.T = &v
}

func (o GetNodeTaskLog200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNodeTaskLog200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.N) {
		toSerialize["n"] = o.N
	}
	if !IsNil(o.T) {
		toSerialize["t"] = o.T
	}
	return toSerialize, nil
}

type NullableGetNodeTaskLog200ResponseDataInner struct {
	value *GetNodeTaskLog200ResponseDataInner
	isSet bool
}

func (v NullableGetNodeTaskLog200ResponseDataInner) Get() *GetNodeTaskLog200ResponseDataInner {
	return v.value
}

func (v *NullableGetNodeTaskLog200ResponseDataInner) Set(val *GetNodeTaskLog200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNodeTaskLog200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNodeTaskLog200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNodeTaskLog200ResponseDataInner(val *GetNodeTaskLog200ResponseDataInner) *NullableGetNodeTaskLog200ResponseDataInner {
	return &NullableGetNodeTaskLog200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetNodeTaskLog200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNodeTaskLog200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


