/*
ProxMox VE API

ProxMox VE API

API version: 8.0
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the GetVMConfig200ResponseDataIvshmem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVMConfig200ResponseDataIvshmem{}

// GetVMConfig200ResponseDataIvshmem struct for GetVMConfig200ResponseDataIvshmem
type GetVMConfig200ResponseDataIvshmem struct {
	// The name of the file. Will be prefixed with 'pve-shm-'. Default is the VMID. Will be deleted when the VM is stopped.
	Name *string `json:"name,omitempty"`
	// The size of the file in MB.
	Size *int64 `json:"size,omitempty"`
}

// NewGetVMConfig200ResponseDataIvshmem instantiates a new GetVMConfig200ResponseDataIvshmem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVMConfig200ResponseDataIvshmem() *GetVMConfig200ResponseDataIvshmem {
	this := GetVMConfig200ResponseDataIvshmem{}
	return &this
}

// NewGetVMConfig200ResponseDataIvshmemWithDefaults instantiates a new GetVMConfig200ResponseDataIvshmem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVMConfig200ResponseDataIvshmemWithDefaults() *GetVMConfig200ResponseDataIvshmem {
	this := GetVMConfig200ResponseDataIvshmem{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetVMConfig200ResponseDataIvshmem) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMConfig200ResponseDataIvshmem) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetVMConfig200ResponseDataIvshmem) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetVMConfig200ResponseDataIvshmem) SetName(v string) {
	o.Name = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *GetVMConfig200ResponseDataIvshmem) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVMConfig200ResponseDataIvshmem) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *GetVMConfig200ResponseDataIvshmem) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *GetVMConfig200ResponseDataIvshmem) SetSize(v int64) {
	o.Size = &v
}

func (o GetVMConfig200ResponseDataIvshmem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVMConfig200ResponseDataIvshmem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	return toSerialize, nil
}

type NullableGetVMConfig200ResponseDataIvshmem struct {
	value *GetVMConfig200ResponseDataIvshmem
	isSet bool
}

func (v NullableGetVMConfig200ResponseDataIvshmem) Get() *GetVMConfig200ResponseDataIvshmem {
	return v.value
}

func (v *NullableGetVMConfig200ResponseDataIvshmem) Set(val *GetVMConfig200ResponseDataIvshmem) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVMConfig200ResponseDataIvshmem) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVMConfig200ResponseDataIvshmem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVMConfig200ResponseDataIvshmem(val *GetVMConfig200ResponseDataIvshmem) *NullableGetVMConfig200ResponseDataIvshmem {
	return &NullableGetVMConfig200ResponseDataIvshmem{value: val, isSet: true}
}

func (v NullableGetVMConfig200ResponseDataIvshmem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVMConfig200ResponseDataIvshmem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


