/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the GetContainerSnapshots200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetContainerSnapshots200Response{}

// GetContainerSnapshots200Response struct for GetContainerSnapshots200Response
type GetContainerSnapshots200Response struct {
	// 
	Data []GetContainerSnapshots200ResponseDataInner `json:"data,omitempty"`
	Errors []string `json:"errors,omitempty"`
}

// NewGetContainerSnapshots200Response instantiates a new GetContainerSnapshots200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetContainerSnapshots200Response() *GetContainerSnapshots200Response {
	this := GetContainerSnapshots200Response{}
	return &this
}

// NewGetContainerSnapshots200ResponseWithDefaults instantiates a new GetContainerSnapshots200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetContainerSnapshots200ResponseWithDefaults() *GetContainerSnapshots200Response {
	this := GetContainerSnapshots200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetContainerSnapshots200Response) GetData() []GetContainerSnapshots200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetContainerSnapshots200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContainerSnapshots200Response) GetDataOk() ([]GetContainerSnapshots200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetContainerSnapshots200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetContainerSnapshots200ResponseDataInner and assigns it to the Data field.
func (o *GetContainerSnapshots200Response) SetData(v []GetContainerSnapshots200ResponseDataInner) {
	o.Data = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *GetContainerSnapshots200Response) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContainerSnapshots200Response) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *GetContainerSnapshots200Response) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *GetContainerSnapshots200Response) SetErrors(v []string) {
	o.Errors = v
}

func (o GetContainerSnapshots200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetContainerSnapshots200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableGetContainerSnapshots200Response struct {
	value *GetContainerSnapshots200Response
	isSet bool
}

func (v NullableGetContainerSnapshots200Response) Get() *GetContainerSnapshots200Response {
	return v.value
}

func (v *NullableGetContainerSnapshots200Response) Set(val *GetContainerSnapshots200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetContainerSnapshots200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetContainerSnapshots200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetContainerSnapshots200Response(val *GetContainerSnapshots200Response) *NullableGetContainerSnapshots200Response {
	return &NullableGetContainerSnapshots200Response{value: val, isSet: true}
}

func (v NullableGetContainerSnapshots200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetContainerSnapshots200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


