/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the CreateVMRequestAgent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVMRequestAgent{}

// CreateVMRequestAgent struct for CreateVMRequestAgent
type CreateVMRequestAgent struct {
	Enabled bool `json:"enabled"`
	FreezeFsOnBackup *bool `json:"freeze-fs-on-backup,omitempty"`
	FstrimClonedDisks *bool `json:"fstrim_cloned_disks,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewCreateVMRequestAgent instantiates a new CreateVMRequestAgent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVMRequestAgent(enabled bool) *CreateVMRequestAgent {
	this := CreateVMRequestAgent{}
	this.Enabled = enabled
	return &this
}

// NewCreateVMRequestAgentWithDefaults instantiates a new CreateVMRequestAgent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVMRequestAgentWithDefaults() *CreateVMRequestAgent {
	this := CreateVMRequestAgent{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *CreateVMRequestAgent) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *CreateVMRequestAgent) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *CreateVMRequestAgent) SetEnabled(v bool) {
	o.Enabled = v
}

// GetFreezeFsOnBackup returns the FreezeFsOnBackup field value if set, zero value otherwise.
func (o *CreateVMRequestAgent) GetFreezeFsOnBackup() bool {
	if o == nil || IsNil(o.FreezeFsOnBackup) {
		var ret bool
		return ret
	}
	return *o.FreezeFsOnBackup
}

// GetFreezeFsOnBackupOk returns a tuple with the FreezeFsOnBackup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestAgent) GetFreezeFsOnBackupOk() (*bool, bool) {
	if o == nil || IsNil(o.FreezeFsOnBackup) {
		return nil, false
	}
	return o.FreezeFsOnBackup, true
}

// HasFreezeFsOnBackup returns a boolean if a field has been set.
func (o *CreateVMRequestAgent) HasFreezeFsOnBackup() bool {
	if o != nil && !IsNil(o.FreezeFsOnBackup) {
		return true
	}

	return false
}

// SetFreezeFsOnBackup gets a reference to the given bool and assigns it to the FreezeFsOnBackup field.
func (o *CreateVMRequestAgent) SetFreezeFsOnBackup(v bool) {
	o.FreezeFsOnBackup = &v
}

// GetFstrimClonedDisks returns the FstrimClonedDisks field value if set, zero value otherwise.
func (o *CreateVMRequestAgent) GetFstrimClonedDisks() bool {
	if o == nil || IsNil(o.FstrimClonedDisks) {
		var ret bool
		return ret
	}
	return *o.FstrimClonedDisks
}

// GetFstrimClonedDisksOk returns a tuple with the FstrimClonedDisks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestAgent) GetFstrimClonedDisksOk() (*bool, bool) {
	if o == nil || IsNil(o.FstrimClonedDisks) {
		return nil, false
	}
	return o.FstrimClonedDisks, true
}

// HasFstrimClonedDisks returns a boolean if a field has been set.
func (o *CreateVMRequestAgent) HasFstrimClonedDisks() bool {
	if o != nil && !IsNil(o.FstrimClonedDisks) {
		return true
	}

	return false
}

// SetFstrimClonedDisks gets a reference to the given bool and assigns it to the FstrimClonedDisks field.
func (o *CreateVMRequestAgent) SetFstrimClonedDisks(v bool) {
	o.FstrimClonedDisks = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateVMRequestAgent) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestAgent) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateVMRequestAgent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateVMRequestAgent) SetType(v string) {
	o.Type = &v
}

func (o CreateVMRequestAgent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVMRequestAgent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	if !IsNil(o.FreezeFsOnBackup) {
		toSerialize["freeze-fs-on-backup"] = o.FreezeFsOnBackup
	}
	if !IsNil(o.FstrimClonedDisks) {
		toSerialize["fstrim_cloned_disks"] = o.FstrimClonedDisks
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableCreateVMRequestAgent struct {
	value *CreateVMRequestAgent
	isSet bool
}

func (v NullableCreateVMRequestAgent) Get() *CreateVMRequestAgent {
	return v.value
}

func (v *NullableCreateVMRequestAgent) Set(val *CreateVMRequestAgent) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVMRequestAgent) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVMRequestAgent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVMRequestAgent(val *CreateVMRequestAgent) *NullableCreateVMRequestAgent {
	return &NullableCreateVMRequestAgent{value: val, isSet: true}
}

func (v NullableCreateVMRequestAgent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVMRequestAgent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


