/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the GetNodeTaskStatus200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNodeTaskStatus200ResponseData{}

// GetNodeTaskStatus200ResponseData 
type GetNodeTaskStatus200ResponseData struct {
	// 
	Exitstatus *string `json:"exitstatus,omitempty"`
	// 
	Id *string `json:"id,omitempty"`
	// 
	Node *string `json:"node,omitempty"`
	// 
	Pid *int64 `json:"pid,omitempty"`
	// 
	Pstart *int64 `json:"pstart,omitempty"`
	// 
	Starttime *int64 `json:"starttime,omitempty"`
	// 
	Status *string `json:"status,omitempty"`
	// 
	Type *string `json:"type,omitempty"`
	// 
	Upid *string `json:"upid,omitempty"`
	// 
	User *string `json:"user,omitempty"`
}

// NewGetNodeTaskStatus200ResponseData instantiates a new GetNodeTaskStatus200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNodeTaskStatus200ResponseData() *GetNodeTaskStatus200ResponseData {
	this := GetNodeTaskStatus200ResponseData{}
	return &this
}

// NewGetNodeTaskStatus200ResponseDataWithDefaults instantiates a new GetNodeTaskStatus200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNodeTaskStatus200ResponseDataWithDefaults() *GetNodeTaskStatus200ResponseData {
	this := GetNodeTaskStatus200ResponseData{}
	return &this
}

// GetExitstatus returns the Exitstatus field value if set, zero value otherwise.
func (o *GetNodeTaskStatus200ResponseData) GetExitstatus() string {
	if o == nil || IsNil(o.Exitstatus) {
		var ret string
		return ret
	}
	return *o.Exitstatus
}

// GetExitstatusOk returns a tuple with the Exitstatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNodeTaskStatus200ResponseData) GetExitstatusOk() (*string, bool) {
	if o == nil || IsNil(o.Exitstatus) {
		return nil, false
	}
	return o.Exitstatus, true
}

// HasExitstatus returns a boolean if a field has been set.
func (o *GetNodeTaskStatus200ResponseData) HasExitstatus() bool {
	if o != nil && !IsNil(o.Exitstatus) {
		return true
	}

	return false
}

// SetExitstatus gets a reference to the given string and assigns it to the Exitstatus field.
func (o *GetNodeTaskStatus200ResponseData) SetExitstatus(v string) {
	o.Exitstatus = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetNodeTaskStatus200ResponseData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNodeTaskStatus200ResponseData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetNodeTaskStatus200ResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetNodeTaskStatus200ResponseData) SetId(v string) {
	o.Id = &v
}

// GetNode returns the Node field value if set, zero value otherwise.
func (o *GetNodeTaskStatus200ResponseData) GetNode() string {
	if o == nil || IsNil(o.Node) {
		var ret string
		return ret
	}
	return *o.Node
}

// GetNodeOk returns a tuple with the Node field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNodeTaskStatus200ResponseData) GetNodeOk() (*string, bool) {
	if o == nil || IsNil(o.Node) {
		return nil, false
	}
	return o.Node, true
}

// HasNode returns a boolean if a field has been set.
func (o *GetNodeTaskStatus200ResponseData) HasNode() bool {
	if o != nil && !IsNil(o.Node) {
		return true
	}

	return false
}

// SetNode gets a reference to the given string and assigns it to the Node field.
func (o *GetNodeTaskStatus200ResponseData) SetNode(v string) {
	o.Node = &v
}

// GetPid returns the Pid field value if set, zero value otherwise.
func (o *GetNodeTaskStatus200ResponseData) GetPid() int64 {
	if o == nil || IsNil(o.Pid) {
		var ret int64
		return ret
	}
	return *o.Pid
}

// GetPidOk returns a tuple with the Pid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNodeTaskStatus200ResponseData) GetPidOk() (*int64, bool) {
	if o == nil || IsNil(o.Pid) {
		return nil, false
	}
	return o.Pid, true
}

// HasPid returns a boolean if a field has been set.
func (o *GetNodeTaskStatus200ResponseData) HasPid() bool {
	if o != nil && !IsNil(o.Pid) {
		return true
	}

	return false
}

// SetPid gets a reference to the given int64 and assigns it to the Pid field.
func (o *GetNodeTaskStatus200ResponseData) SetPid(v int64) {
	o.Pid = &v
}

// GetPstart returns the Pstart field value if set, zero value otherwise.
func (o *GetNodeTaskStatus200ResponseData) GetPstart() int64 {
	if o == nil || IsNil(o.Pstart) {
		var ret int64
		return ret
	}
	return *o.Pstart
}

// GetPstartOk returns a tuple with the Pstart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNodeTaskStatus200ResponseData) GetPstartOk() (*int64, bool) {
	if o == nil || IsNil(o.Pstart) {
		return nil, false
	}
	return o.Pstart, true
}

// HasPstart returns a boolean if a field has been set.
func (o *GetNodeTaskStatus200ResponseData) HasPstart() bool {
	if o != nil && !IsNil(o.Pstart) {
		return true
	}

	return false
}

// SetPstart gets a reference to the given int64 and assigns it to the Pstart field.
func (o *GetNodeTaskStatus200ResponseData) SetPstart(v int64) {
	o.Pstart = &v
}

// GetStarttime returns the Starttime field value if set, zero value otherwise.
func (o *GetNodeTaskStatus200ResponseData) GetStarttime() int64 {
	if o == nil || IsNil(o.Starttime) {
		var ret int64
		return ret
	}
	return *o.Starttime
}

// GetStarttimeOk returns a tuple with the Starttime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNodeTaskStatus200ResponseData) GetStarttimeOk() (*int64, bool) {
	if o == nil || IsNil(o.Starttime) {
		return nil, false
	}
	return o.Starttime, true
}

// HasStarttime returns a boolean if a field has been set.
func (o *GetNodeTaskStatus200ResponseData) HasStarttime() bool {
	if o != nil && !IsNil(o.Starttime) {
		return true
	}

	return false
}

// SetStarttime gets a reference to the given int64 and assigns it to the Starttime field.
func (o *GetNodeTaskStatus200ResponseData) SetStarttime(v int64) {
	o.Starttime = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetNodeTaskStatus200ResponseData) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNodeTaskStatus200ResponseData) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetNodeTaskStatus200ResponseData) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetNodeTaskStatus200ResponseData) SetStatus(v string) {
	o.Status = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetNodeTaskStatus200ResponseData) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNodeTaskStatus200ResponseData) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetNodeTaskStatus200ResponseData) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetNodeTaskStatus200ResponseData) SetType(v string) {
	o.Type = &v
}

// GetUpid returns the Upid field value if set, zero value otherwise.
func (o *GetNodeTaskStatus200ResponseData) GetUpid() string {
	if o == nil || IsNil(o.Upid) {
		var ret string
		return ret
	}
	return *o.Upid
}

// GetUpidOk returns a tuple with the Upid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNodeTaskStatus200ResponseData) GetUpidOk() (*string, bool) {
	if o == nil || IsNil(o.Upid) {
		return nil, false
	}
	return o.Upid, true
}

// HasUpid returns a boolean if a field has been set.
func (o *GetNodeTaskStatus200ResponseData) HasUpid() bool {
	if o != nil && !IsNil(o.Upid) {
		return true
	}

	return false
}

// SetUpid gets a reference to the given string and assigns it to the Upid field.
func (o *GetNodeTaskStatus200ResponseData) SetUpid(v string) {
	o.Upid = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *GetNodeTaskStatus200ResponseData) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNodeTaskStatus200ResponseData) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *GetNodeTaskStatus200ResponseData) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *GetNodeTaskStatus200ResponseData) SetUser(v string) {
	o.User = &v
}

func (o GetNodeTaskStatus200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNodeTaskStatus200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Exitstatus) {
		toSerialize["exitstatus"] = o.Exitstatus
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Node) {
		toSerialize["node"] = o.Node
	}
	if !IsNil(o.Pid) {
		toSerialize["pid"] = o.Pid
	}
	if !IsNil(o.Pstart) {
		toSerialize["pstart"] = o.Pstart
	}
	if !IsNil(o.Starttime) {
		toSerialize["starttime"] = o.Starttime
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Upid) {
		toSerialize["upid"] = o.Upid
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullableGetNodeTaskStatus200ResponseData struct {
	value *GetNodeTaskStatus200ResponseData
	isSet bool
}

func (v NullableGetNodeTaskStatus200ResponseData) Get() *GetNodeTaskStatus200ResponseData {
	return v.value
}

func (v *NullableGetNodeTaskStatus200ResponseData) Set(val *GetNodeTaskStatus200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNodeTaskStatus200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNodeTaskStatus200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNodeTaskStatus200ResponseData(val *GetNodeTaskStatus200ResponseData) *NullableGetNodeTaskStatus200ResponseData {
	return &NullableGetNodeTaskStatus200ResponseData{value: val, isSet: true}
}

func (v NullableGetNodeTaskStatus200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNodeTaskStatus200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


