/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the CreateVMRequestBoot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVMRequestBoot{}

// CreateVMRequestBoot struct for CreateVMRequestBoot
type CreateVMRequestBoot struct {
	Order *string `json:"order,omitempty"`
}

// NewCreateVMRequestBoot instantiates a new CreateVMRequestBoot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVMRequestBoot() *CreateVMRequestBoot {
	this := CreateVMRequestBoot{}
	return &this
}

// NewCreateVMRequestBootWithDefaults instantiates a new CreateVMRequestBoot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVMRequestBootWithDefaults() *CreateVMRequestBoot {
	this := CreateVMRequestBoot{}
	return &this
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *CreateVMRequestBoot) GetOrder() string {
	if o == nil || IsNil(o.Order) {
		var ret string
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVMRequestBoot) GetOrderOk() (*string, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *CreateVMRequestBoot) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given string and assigns it to the Order field.
func (o *CreateVMRequestBoot) SetOrder(v string) {
	o.Order = &v
}

func (o CreateVMRequestBoot) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVMRequestBoot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	return toSerialize, nil
}

type NullableCreateVMRequestBoot struct {
	value *CreateVMRequestBoot
	isSet bool
}

func (v NullableCreateVMRequestBoot) Get() *CreateVMRequestBoot {
	return v.value
}

func (v *NullableCreateVMRequestBoot) Set(val *CreateVMRequestBoot) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVMRequestBoot) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVMRequestBoot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVMRequestBoot(val *CreateVMRequestBoot) *NullableCreateVMRequestBoot {
	return &NullableCreateVMRequestBoot{value: val, isSet: true}
}

func (v NullableCreateVMRequestBoot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVMRequestBoot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


