/*
ProxMox VE API

ProxMox VE API

API version: 8.3
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the CreateNodesSingleStorageSingleContent200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNodesSingleStorageSingleContent200Response{}

// CreateNodesSingleStorageSingleContent200Response struct for CreateNodesSingleStorageSingleContent200Response
type CreateNodesSingleStorageSingleContent200Response struct {
	Errors []string `json:"errors,omitempty"`
	// Volume identifier
	Data *string `json:"data,omitempty"`
}

// NewCreateNodesSingleStorageSingleContent200Response instantiates a new CreateNodesSingleStorageSingleContent200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNodesSingleStorageSingleContent200Response() *CreateNodesSingleStorageSingleContent200Response {
	this := CreateNodesSingleStorageSingleContent200Response{}
	return &this
}

// NewCreateNodesSingleStorageSingleContent200ResponseWithDefaults instantiates a new CreateNodesSingleStorageSingleContent200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNodesSingleStorageSingleContent200ResponseWithDefaults() *CreateNodesSingleStorageSingleContent200Response {
	this := CreateNodesSingleStorageSingleContent200Response{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *CreateNodesSingleStorageSingleContent200Response) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNodesSingleStorageSingleContent200Response) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *CreateNodesSingleStorageSingleContent200Response) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *CreateNodesSingleStorageSingleContent200Response) SetErrors(v []string) {
	o.Errors = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateNodesSingleStorageSingleContent200Response) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNodesSingleStorageSingleContent200Response) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateNodesSingleStorageSingleContent200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *CreateNodesSingleStorageSingleContent200Response) SetData(v string) {
	o.Data = &v
}

func (o CreateNodesSingleStorageSingleContent200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNodesSingleStorageSingleContent200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateNodesSingleStorageSingleContent200Response struct {
	value *CreateNodesSingleStorageSingleContent200Response
	isSet bool
}

func (v NullableCreateNodesSingleStorageSingleContent200Response) Get() *CreateNodesSingleStorageSingleContent200Response {
	return v.value
}

func (v *NullableCreateNodesSingleStorageSingleContent200Response) Set(val *CreateNodesSingleStorageSingleContent200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNodesSingleStorageSingleContent200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNodesSingleStorageSingleContent200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNodesSingleStorageSingleContent200Response(val *CreateNodesSingleStorageSingleContent200Response) *NullableCreateNodesSingleStorageSingleContent200Response {
	return &NullableCreateNodesSingleStorageSingleContent200Response{value: val, isSet: true}
}

func (v NullableCreateNodesSingleStorageSingleContent200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNodesSingleStorageSingleContent200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


