/*
ProxMox VE API

ProxMox VE API

API version: 8.0
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the GetClusterConfigNodes200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetClusterConfigNodes200ResponseDataInner{}

// GetClusterConfigNodes200ResponseDataInner struct for GetClusterConfigNodes200ResponseDataInner
type GetClusterConfigNodes200ResponseDataInner struct {
	Node *string `json:"node,omitempty"`
}

// NewGetClusterConfigNodes200ResponseDataInner instantiates a new GetClusterConfigNodes200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClusterConfigNodes200ResponseDataInner() *GetClusterConfigNodes200ResponseDataInner {
	this := GetClusterConfigNodes200ResponseDataInner{}
	return &this
}

// NewGetClusterConfigNodes200ResponseDataInnerWithDefaults instantiates a new GetClusterConfigNodes200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClusterConfigNodes200ResponseDataInnerWithDefaults() *GetClusterConfigNodes200ResponseDataInner {
	this := GetClusterConfigNodes200ResponseDataInner{}
	return &this
}

// GetNode returns the Node field value if set, zero value otherwise.
func (o *GetClusterConfigNodes200ResponseDataInner) GetNode() string {
	if o == nil || IsNil(o.Node) {
		var ret string
		return ret
	}
	return *o.Node
}

// GetNodeOk returns a tuple with the Node field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetClusterConfigNodes200ResponseDataInner) GetNodeOk() (*string, bool) {
	if o == nil || IsNil(o.Node) {
		return nil, false
	}
	return o.Node, true
}

// HasNode returns a boolean if a field has been set.
func (o *GetClusterConfigNodes200ResponseDataInner) HasNode() bool {
	if o != nil && !IsNil(o.Node) {
		return true
	}

	return false
}

// SetNode gets a reference to the given string and assigns it to the Node field.
func (o *GetClusterConfigNodes200ResponseDataInner) SetNode(v string) {
	o.Node = &v
}

func (o GetClusterConfigNodes200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetClusterConfigNodes200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Node) {
		toSerialize["node"] = o.Node
	}
	return toSerialize, nil
}

type NullableGetClusterConfigNodes200ResponseDataInner struct {
	value *GetClusterConfigNodes200ResponseDataInner
	isSet bool
}

func (v NullableGetClusterConfigNodes200ResponseDataInner) Get() *GetClusterConfigNodes200ResponseDataInner {
	return v.value
}

func (v *NullableGetClusterConfigNodes200ResponseDataInner) Set(val *GetClusterConfigNodes200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClusterConfigNodes200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClusterConfigNodes200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClusterConfigNodes200ResponseDataInner(val *GetClusterConfigNodes200ResponseDataInner) *NullableGetClusterConfigNodes200ResponseDataInner {
	return &NullableGetClusterConfigNodes200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetClusterConfigNodes200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClusterConfigNodes200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


