/*
ProxMox VE API

ProxMox VE API

API version: 8.0
Contact: baldur@email.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pxapiobject

import (
	"encoding/json"
)

// checks if the GetContainers200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetContainers200ResponseDataInner{}

// GetContainers200ResponseDataInner struct for GetContainers200ResponseDataInner
type GetContainers200ResponseDataInner struct {
	// Maximum usable CPUs.
	Cpus *float32 `json:"cpus,omitempty"`
	// The current config lock, if any.
	Lock *string `json:"lock,omitempty"`
	// Root disk size in bytes.
	Maxdisk *int64 `json:"maxdisk,omitempty"`
	// Maximum memory in bytes.
	Maxmem *int64 `json:"maxmem,omitempty"`
	// Maximum SWAP memory in bytes.
	Maxswap *int64 `json:"maxswap,omitempty"`
	// Container name.
	Name *string `json:"name,omitempty"`
	// LXC Container status.
	Status *string `json:"status,omitempty"`
	// The current configured tags, if any.
	Tags *string `json:"tags,omitempty"`
	// Uptime.
	Uptime *int64 `json:"uptime,omitempty"`
	// The (unique) ID of the VM.
	Vmid *int64 `json:"vmid,omitempty"`
}

// NewGetContainers200ResponseDataInner instantiates a new GetContainers200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetContainers200ResponseDataInner() *GetContainers200ResponseDataInner {
	this := GetContainers200ResponseDataInner{}
	return &this
}

// NewGetContainers200ResponseDataInnerWithDefaults instantiates a new GetContainers200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetContainers200ResponseDataInnerWithDefaults() *GetContainers200ResponseDataInner {
	this := GetContainers200ResponseDataInner{}
	return &this
}

// GetCpus returns the Cpus field value if set, zero value otherwise.
func (o *GetContainers200ResponseDataInner) GetCpus() float32 {
	if o == nil || IsNil(o.Cpus) {
		var ret float32
		return ret
	}
	return *o.Cpus
}

// GetCpusOk returns a tuple with the Cpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContainers200ResponseDataInner) GetCpusOk() (*float32, bool) {
	if o == nil || IsNil(o.Cpus) {
		return nil, false
	}
	return o.Cpus, true
}

// HasCpus returns a boolean if a field has been set.
func (o *GetContainers200ResponseDataInner) HasCpus() bool {
	if o != nil && !IsNil(o.Cpus) {
		return true
	}

	return false
}

// SetCpus gets a reference to the given float32 and assigns it to the Cpus field.
func (o *GetContainers200ResponseDataInner) SetCpus(v float32) {
	o.Cpus = &v
}

// GetLock returns the Lock field value if set, zero value otherwise.
func (o *GetContainers200ResponseDataInner) GetLock() string {
	if o == nil || IsNil(o.Lock) {
		var ret string
		return ret
	}
	return *o.Lock
}

// GetLockOk returns a tuple with the Lock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContainers200ResponseDataInner) GetLockOk() (*string, bool) {
	if o == nil || IsNil(o.Lock) {
		return nil, false
	}
	return o.Lock, true
}

// HasLock returns a boolean if a field has been set.
func (o *GetContainers200ResponseDataInner) HasLock() bool {
	if o != nil && !IsNil(o.Lock) {
		return true
	}

	return false
}

// SetLock gets a reference to the given string and assigns it to the Lock field.
func (o *GetContainers200ResponseDataInner) SetLock(v string) {
	o.Lock = &v
}

// GetMaxdisk returns the Maxdisk field value if set, zero value otherwise.
func (o *GetContainers200ResponseDataInner) GetMaxdisk() int64 {
	if o == nil || IsNil(o.Maxdisk) {
		var ret int64
		return ret
	}
	return *o.Maxdisk
}

// GetMaxdiskOk returns a tuple with the Maxdisk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContainers200ResponseDataInner) GetMaxdiskOk() (*int64, bool) {
	if o == nil || IsNil(o.Maxdisk) {
		return nil, false
	}
	return o.Maxdisk, true
}

// HasMaxdisk returns a boolean if a field has been set.
func (o *GetContainers200ResponseDataInner) HasMaxdisk() bool {
	if o != nil && !IsNil(o.Maxdisk) {
		return true
	}

	return false
}

// SetMaxdisk gets a reference to the given int64 and assigns it to the Maxdisk field.
func (o *GetContainers200ResponseDataInner) SetMaxdisk(v int64) {
	o.Maxdisk = &v
}

// GetMaxmem returns the Maxmem field value if set, zero value otherwise.
func (o *GetContainers200ResponseDataInner) GetMaxmem() int64 {
	if o == nil || IsNil(o.Maxmem) {
		var ret int64
		return ret
	}
	return *o.Maxmem
}

// GetMaxmemOk returns a tuple with the Maxmem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContainers200ResponseDataInner) GetMaxmemOk() (*int64, bool) {
	if o == nil || IsNil(o.Maxmem) {
		return nil, false
	}
	return o.Maxmem, true
}

// HasMaxmem returns a boolean if a field has been set.
func (o *GetContainers200ResponseDataInner) HasMaxmem() bool {
	if o != nil && !IsNil(o.Maxmem) {
		return true
	}

	return false
}

// SetMaxmem gets a reference to the given int64 and assigns it to the Maxmem field.
func (o *GetContainers200ResponseDataInner) SetMaxmem(v int64) {
	o.Maxmem = &v
}

// GetMaxswap returns the Maxswap field value if set, zero value otherwise.
func (o *GetContainers200ResponseDataInner) GetMaxswap() int64 {
	if o == nil || IsNil(o.Maxswap) {
		var ret int64
		return ret
	}
	return *o.Maxswap
}

// GetMaxswapOk returns a tuple with the Maxswap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContainers200ResponseDataInner) GetMaxswapOk() (*int64, bool) {
	if o == nil || IsNil(o.Maxswap) {
		return nil, false
	}
	return o.Maxswap, true
}

// HasMaxswap returns a boolean if a field has been set.
func (o *GetContainers200ResponseDataInner) HasMaxswap() bool {
	if o != nil && !IsNil(o.Maxswap) {
		return true
	}

	return false
}

// SetMaxswap gets a reference to the given int64 and assigns it to the Maxswap field.
func (o *GetContainers200ResponseDataInner) SetMaxswap(v int64) {
	o.Maxswap = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetContainers200ResponseDataInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContainers200ResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetContainers200ResponseDataInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetContainers200ResponseDataInner) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetContainers200ResponseDataInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContainers200ResponseDataInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetContainers200ResponseDataInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetContainers200ResponseDataInner) SetStatus(v string) {
	o.Status = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *GetContainers200ResponseDataInner) GetTags() string {
	if o == nil || IsNil(o.Tags) {
		var ret string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContainers200ResponseDataInner) GetTagsOk() (*string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *GetContainers200ResponseDataInner) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given string and assigns it to the Tags field.
func (o *GetContainers200ResponseDataInner) SetTags(v string) {
	o.Tags = &v
}

// GetUptime returns the Uptime field value if set, zero value otherwise.
func (o *GetContainers200ResponseDataInner) GetUptime() int64 {
	if o == nil || IsNil(o.Uptime) {
		var ret int64
		return ret
	}
	return *o.Uptime
}

// GetUptimeOk returns a tuple with the Uptime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContainers200ResponseDataInner) GetUptimeOk() (*int64, bool) {
	if o == nil || IsNil(o.Uptime) {
		return nil, false
	}
	return o.Uptime, true
}

// HasUptime returns a boolean if a field has been set.
func (o *GetContainers200ResponseDataInner) HasUptime() bool {
	if o != nil && !IsNil(o.Uptime) {
		return true
	}

	return false
}

// SetUptime gets a reference to the given int64 and assigns it to the Uptime field.
func (o *GetContainers200ResponseDataInner) SetUptime(v int64) {
	o.Uptime = &v
}

// GetVmid returns the Vmid field value if set, zero value otherwise.
func (o *GetContainers200ResponseDataInner) GetVmid() int64 {
	if o == nil || IsNil(o.Vmid) {
		var ret int64
		return ret
	}
	return *o.Vmid
}

// GetVmidOk returns a tuple with the Vmid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetContainers200ResponseDataInner) GetVmidOk() (*int64, bool) {
	if o == nil || IsNil(o.Vmid) {
		return nil, false
	}
	return o.Vmid, true
}

// HasVmid returns a boolean if a field has been set.
func (o *GetContainers200ResponseDataInner) HasVmid() bool {
	if o != nil && !IsNil(o.Vmid) {
		return true
	}

	return false
}

// SetVmid gets a reference to the given int64 and assigns it to the Vmid field.
func (o *GetContainers200ResponseDataInner) SetVmid(v int64) {
	o.Vmid = &v
}

func (o GetContainers200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetContainers200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cpus) {
		toSerialize["cpus"] = o.Cpus
	}
	if !IsNil(o.Lock) {
		toSerialize["lock"] = o.Lock
	}
	if !IsNil(o.Maxdisk) {
		toSerialize["maxdisk"] = o.Maxdisk
	}
	if !IsNil(o.Maxmem) {
		toSerialize["maxmem"] = o.Maxmem
	}
	if !IsNil(o.Maxswap) {
		toSerialize["maxswap"] = o.Maxswap
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Uptime) {
		toSerialize["uptime"] = o.Uptime
	}
	if !IsNil(o.Vmid) {
		toSerialize["vmid"] = o.Vmid
	}
	return toSerialize, nil
}

type NullableGetContainers200ResponseDataInner struct {
	value *GetContainers200ResponseDataInner
	isSet bool
}

func (v NullableGetContainers200ResponseDataInner) Get() *GetContainers200ResponseDataInner {
	return v.value
}

func (v *NullableGetContainers200ResponseDataInner) Set(val *GetContainers200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetContainers200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetContainers200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetContainers200ResponseDataInner(val *GetContainers200ResponseDataInner) *NullableGetContainers200ResponseDataInner {
	return &NullableGetContainers200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetContainers200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetContainers200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


